In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef
import json

In [2]:
datasets = ['processed_Autism Screening Adult.csv',
 'processed_Chess (King-Rook vs. King-Pawn).csv',
 'processed_Cylinder Bands.csv',
 'processed_Diabetic Retinopathy Debrecen.csv',
 'processed_Early Stage Diabetes Risk.csv',
 'processed_Estimation of obesity levels based on eating habits and physical condition.csv',
 'processed_Hepatitis.csv',
 'processed_Hepatocellular Carcinoma.csv',
 'processed_Primary Tumor.csv',
 'processed_Audiology (Standardized).csv',
 'processed_Cardiotocography.csv',
 'processed_Cervical Cancer.csv',
 'processed_Dermatology.csv',
 'processed_Thoracic Surgery.csv',
 'processed_Credit Approval.csv',
 'processed_HCV.csv',
 'processed_Parkinsons.csv',
 'processed_QSAR Bioconcentration classes.csv',
 'processed_Thyroid Disease.csv',
 'processed_Lymphography.csv',
 'processed_Breast Cancer Wisconsin (Diagnostic).csv']

datasets

['processed_Autism Screening Adult.csv',
 'processed_Chess (King-Rook vs. King-Pawn).csv',
 'processed_Cylinder Bands.csv',
 'processed_Diabetic Retinopathy Debrecen.csv',
 'processed_Early Stage Diabetes Risk.csv',
 'processed_Estimation of obesity levels based on eating habits and physical condition.csv',
 'processed_Hepatitis.csv',
 'processed_Hepatocellular Carcinoma.csv',
 'processed_Primary Tumor.csv',
 'processed_Audiology (Standardized).csv',
 'processed_Cardiotocography.csv',
 'processed_Cervical Cancer.csv',
 'processed_Dermatology.csv',
 'processed_Thoracic Surgery.csv',
 'processed_Credit Approval.csv',
 'processed_HCV.csv',
 'processed_Parkinsons.csv',
 'processed_QSAR Bioconcentration classes.csv',
 'processed_Thyroid Disease.csv',
 'processed_Lymphography.csv',
 'processed_Breast Cancer Wisconsin (Diagnostic).csv']

In [3]:
# parse all the lists from the string representation    
STR = """
[0, 3, 9, 12, 15, 17]
[0, 1, 3, 4, 6, 7, 9, 10, 11, 13, 14, 16, 17, 20, 22, 23, 24, 25, 27, 30, 32, 35]
[0, 1, 2, 3, 4, 5, 9, 10, 15, 20, 21, 23, 24, 25, 27, 28, 29, 32, 33, 34, 35, 36]
[0, 1, 2, 6, 7, 9, 10, 11, 12, 14, 16, 17, 18]
[0, 1, 2, 3, 5, 8, 9, 11, 13, 14]
[1, 2, 3, 5, 6, 7, 10, 15]
[0, 3, 4, 6, 11]
[1, 2, 3, 5, 8, 9, 11, 12, 14, 15, 17, 18, 20, 21, 22, 24, 26, 27, 28, 30, 33, 35, 39, 40, 41, 43, 44, 48]
[2, 6, 7, 8, 9, 10, 12, 13, 16]
[0, 3, 4, 5, 6, 7, 10, 12, 14, 16, 17, 19, 22, 24, 27, 28, 30, 32, 34, 37, 41, 42, 43, 44, 48, 49, 50, 52, 53, 55, 58, 61]
[0, 6, 9, 11, 13, 19, 21]
[2, 3, 4, 8, 17, 22, 23, 24, 30, 31]
[1, 2, 4, 6, 7, 10, 15, 16, 17, 18, 19, 21, 24, 25, 26, 27, 32]
[1, 2, 4, 6, 9, 10, 11, 13, 15]
[1, 2, 3, 5, 7, 8, 10, 12, 13, 14]
[2, 3, 4, 5, 8, 9, 10, 11]
[0, 1, 2, 3, 9, 12]
[1, 3, 5, 6, 8, 10]
[0, 2, 3, 4, 5, 7, 11, 14, 16, 18, 19, 20, 22]
[1, 4, 6, 8, 9, 10, 14, 15, 17]
[0, 1, 3, 4, 11, 13, 14, 19, 21, 23, 24, 25]
"""

qefs127 = [eval(line) for line in STR.strip().split('\n')]

qefs127

[[0, 3, 9, 12, 15, 17],
 [0,
  1,
  3,
  4,
  6,
  7,
  9,
  10,
  11,
  13,
  14,
  16,
  17,
  20,
  22,
  23,
  24,
  25,
  27,
  30,
  32,
  35],
 [0,
  1,
  2,
  3,
  4,
  5,
  9,
  10,
  15,
  20,
  21,
  23,
  24,
  25,
  27,
  28,
  29,
  32,
  33,
  34,
  35,
  36],
 [0, 1, 2, 6, 7, 9, 10, 11, 12, 14, 16, 17, 18],
 [0, 1, 2, 3, 5, 8, 9, 11, 13, 14],
 [1, 2, 3, 5, 6, 7, 10, 15],
 [0, 3, 4, 6, 11],
 [1,
  2,
  3,
  5,
  8,
  9,
  11,
  12,
  14,
  15,
  17,
  18,
  20,
  21,
  22,
  24,
  26,
  27,
  28,
  30,
  33,
  35,
  39,
  40,
  41,
  43,
  44,
  48],
 [2, 6, 7, 8, 9, 10, 12, 13, 16],
 [0,
  3,
  4,
  5,
  6,
  7,
  10,
  12,
  14,
  16,
  17,
  19,
  22,
  24,
  27,
  28,
  30,
  32,
  34,
  37,
  41,
  42,
  43,
  44,
  48,
  49,
  50,
  52,
  53,
  55,
  58,
  61],
 [0, 6, 9, 11, 13, 19, 21],
 [2, 3, 4, 8, 17, 22, 23, 24, 30, 31],
 [1, 2, 4, 6, 7, 10, 15, 16, 17, 18, 19, 21, 24, 25, 26, 27, 32],
 [1, 2, 4, 6, 9, 10, 11, 13, 15],
 [1, 2, 3, 5, 7, 8, 10, 12, 13, 14],
 [2, 3, 4, 5, 8, 9, 10, 11],
 [0, 1, 2, 3, 9, 12],
 [1, 3, 5, 6, 8, 10],
 [0, 2, 3, 4, 5, 7, 11, 14, 16, 18, 19, 20, 22],
 [1, 4, 6, 8, 9, 10, 14, 15, 17],
 [0, 1, 3, 4, 11, 13, 14, 19, 21, 23, 24, 25]]

In [4]:
algo = "aco"
aco = """
[ 6 14 17]
[ 0 1 4 5 7 8 9 10 11 12 14 15 16 20 22 29 31 32 34]
[ 3 4 6 9 10 11 12 13 14 16 17 18 20 21 23 25 28 32 35 36 37]
[ 2 3 5 7 14 18]
[ 0 1 2 3 5 7 8 10 11 13]
[0 2 3 4]
[ 0 1 3 4 11 12 13 15]
[ 0 2 3 4 6 9 11 12 13 15 17 21 22 23 24 25 27 28 30 31 34 41 44 45 48]
[ 3 10 14]
[ 0 1 4 5 6 7 8 10 13 14 17 22 25 26 27 34 35 36 38 41 47 49 50 51 52 53 54 55 58 59 61]
[ 3 6 15 16 18 19 20 21]
[ 0 1 3 5 7 8 13 17 18 22 25 31]
[ 1 4 6 11 14 15 21 22 25 27 33]
[ 1 2 7 12 15]
[ 2  4  8  9 11 12 13 14]
[ 0  2  3  4  5  6  8  9 10]
[ 1  3  6 11 12]
[ 0  1  4  5  6  7  8  9 10]
[ 0  6 14 16 18 21 22]
[ 1  5 12 13 14 15 17]
[ 1 2 8 12 17 18 19 22 23 24]
"""
# features = [[int(num) for num in line.strip().split(" ")] for line in aco.strip().replace("[","").replace("]","").replace("[ ","").split('\n')]
# features

def get_features(STR):
    return [[int(num) for num in line.strip().split(" ")] for line in STR.strip().replace("[","").replace("]","").replace("[ ","").replace("  "," ").split('\n')]


aco_features = get_features(aco)
aco_features

[[6, 14, 17],
 [0, 1, 4, 5, 7, 8, 9, 10, 11, 12, 14, 15, 16, 20, 22, 29, 31, 32, 34],
 [3,
  4,
  6,
  9,
  10,
  11,
  12,
  13,
  14,
  16,
  17,
  18,
  20,
  21,
  23,
  25,
  28,
  32,
  35,
  36,
  37],
 [2, 3, 5, 7, 14, 18],
 [0, 1, 2, 3, 5, 7, 8, 10, 11, 13],
 [0, 2, 3, 4],
 [0, 1, 3, 4, 11, 12, 13, 15],
 [0,
  2,
  3,
  4,
  6,
  9,
  11,
  12,
  13,
  15,
  17,
  21,
  22,
  23,
  24,
  25,
  27,
  28,
  30,
  31,
  34,
  41,
  44,
  45,
  48],
 [3, 10, 14],
 [0,
  1,
  4,
  5,
  6,
  7,
  8,
  10,
  13,
  14,
  17,
  22,
  25,
  26,
  27,
  34,
  35,
  36,
  38,
  41,
  47,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  58,
  59,
  61],
 [3, 6, 15, 16, 18, 19, 20, 21],
 [0, 1, 3, 5, 7, 8, 13, 17, 18, 22, 25, 31],
 [1, 4, 6, 11, 14, 15, 21, 22, 25, 27, 33],
 [1, 2, 7, 12, 15],
 [2, 4, 8, 9, 11, 12, 13, 14],
 [0, 2, 3, 4, 5, 6, 8, 9, 10],
 [1, 3, 6, 11, 12],
 [0, 1, 4, 5, 6, 7, 8, 9, 10],
 [0, 6, 14, 16, 18, 21, 22],
 [1, 5, 12, 13, 14, 15, 17],
 [1, 2, 8, 12, 17, 18, 19, 22, 23, 24]]

In [5]:
imbal_path = "./manually_segregated-mar_7/imbalanced_smotted"
bal_path = "./manually_segregated-mar_7/nearly_balanced"

In [6]:
from sklearn.preprocessing import StandardScaler

In [12]:
save_dir = "./MCC_F1_results/high_dim"

In [8]:
def get_metrics(df, feature_indices):
    X = df.iloc[:, feature_indices]
    target = df.columns[-1]
    y = df[target]

    # Split data into train and test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    
    scaler = StandardScaler()
    train_x_sc = scaler.fit_transform(X_train)
    test_x_sc = scaler.transform(X_test)

    model = RandomForestClassifier(n_estimators=100, random_state=42)

    model.fit(train_x_sc, y_train)
    y_pred = model.predict(test_x_sc)
    accuracy = accuracy_score(y_test, y_pred)
    
    f1 = f1_score(y_test, y_pred, average='weighted')
    mcc = matthews_corrcoef(y_test, y_pred)
    
    return {"accuracy":accuracy, "f1":f1, "mcc":mcc}

In [13]:

import os

def save_results(algo, features, datasets = datasets, save_dir="./MCC_F1_results/high_dim"):
    result = {'bal':{}, 'imbal':{}}

    for i,dataset in enumerate(datasets): 
        path_bal = f"{bal_path}/{dataset}"
        path_imbal = f"{imbal_path}/{dataset}"

        try:
            bal = False
            if(os.path.exists(path_bal)):
                data = pd.read_csv(path_bal)
                bal = True
            else:
                data = pd.read_csv(path_imbal)

            metrics = get_metrics(data, features[i])
            if(bal):
                result['bal'][dataset] = metrics
            else:
                result['imbal'][dataset] = metrics
            
            print(f"Processed {dataset}: {metrics}")
        except Exception as e: 
            print(f"Error reading {dataset}: {e}")
            continue

    with open(f"{save_dir}/{algo}.json", "w") as f:
        json.dump(result, f, indent=4)

In [14]:
save_results("aco", aco_features)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9739311783107404, 'f1': 0.973948550239587, 'mcc': 0.9484027528886612}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8895705521472392, 'f1': 0.8884166840775705, 'mcc': 0.7799696385415915}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7283236994219653, 'f1': 0.7284795191625127, 'mcc': 0.45139879222918877}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9558359621451105, 'f1': 0.9558556193495463, 'mcc': 0.9485202943821591}
Processed processed_Hepatitis.csv: {'accuracy': 0.8378378378378378, 'f1': 0.837234555984556, 'mcc': 0.670904674744761}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7096774193548387, 'f1': 0.7114976236222066, 'mcc': 0.4304142310105583}
Processed processed_Primary Tumor.csv: {'accuracy': 0.21320754716981133, 'f1': 0.11596990981559248, 'mcc': 0.20250199333368402}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9826589595375722, 'f1': 0.9825356235456633, 'mcc': 0.9819329736319492}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9946308724832215, 'f1': 0.994630645309478, 'mcc': 0.9919418759074042}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.9813278008298755, 'f1': 0.9813338345264351, 'mcc': 0.9628310223209914}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8583333333333333, 'f1': 0.858323494687131, 'mcc': 0.7167662244453878}
Processed processed_Credit Approval.csv: {'accuracy': 0.8985507246376812, 'f1': 0.8984363968087564, 'mcc': 0.7962635300467855}
Processed processed_HCV.csv: {'accuracy': 0.99375, 'f1': 0.993723558580647, 'mcc': 0.9922134858216433}
Processed processed_Parkinsons.csv: {'accuracy': 0.9550561797752809, 'f1': 0.9552160409244542, 'mcc': 0.9134651633484239}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8671497584541062, 'f1': 0.8675780939883346, 'mcc': 0.8005014477871684}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.9819976771196284, 'f1': 0.9819976589065375, 'mcc': 0.9640013030856008}
Processed processed_Lymphography.csv: {'accuracy': 0.9693877551020408, 'f1': 0.9693755053041626, 'mcc': 0.9592999120193504}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9941520467836257, 'f1': 0.9941421295173417, 'mcc': 0.9874706558674105}

In [15]:
algo = "bes"
STR = """
[ 7 17]
[ 0 5 6 8 9 11 12 13 14 15 16 17 19 20 21 22 24 25 28 29 30 31 32 34 35]
[ 0 2 3 5 6 7 8 10 12 15 19 20 21 22 24 28 34 35]
[ 1 2 3 4 5 6 10 12 13 14 15]
[ 0 1 2 3 5 6 8 10 12 14]
[2 3]
[ 0 1 2 3 4 9 10 11 13 15]
[ 2 3 7 8 10 13 16 17 19 21 23 29 30 31 32 35 41 47 48]
[ 2 7 8 9 10 14 16]
[ 0 1 3 5 6 10 13 14 15 18 21 24 25 30 33 34 38 42 44 46 47 49 50 52 53 55 57 58 60 61]
[ 1 2 3 6 8 18 20 21]
[ 0 6 7 11 16 18 19 26 29 31 32]
[ 3 4 5 7 8 11 14 21 22 23 25 26 30 31]
[ 1 2 4 5 9 11 14 15]
[ 0  1  2  3  4  6  8 10 12 13 14]
[ 2  3  4  5  6 10 11]
[ 0  1  2  6 11]
[ 1  3  4  5  7  9 10]
[ 0  6  9 10 11 14 16 18 19 20]
[ 1  4  5  6 11 12 13 14 15]
[ 0 1 3 4 9 12 17 19 21 23 24 26]"""

bes = get_features(STR)
bes

[[7, 17],
 [0,
  5,
  6,
  8,
  9,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  19,
  20,
  21,
  22,
  24,
  25,
  28,
  29,
  30,
  31,
  32,
  34,
  35],
 [0, 2, 3, 5, 6, 7, 8, 10, 12, 15, 19, 20, 21, 22, 24, 28, 34, 35],
 [1, 2, 3, 4, 5, 6, 10, 12, 13, 14, 15],
 [0, 1, 2, 3, 5, 6, 8, 10, 12, 14],
 [2, 3],
 [0, 1, 2, 3, 4, 9, 10, 11, 13, 15],
 [2, 3, 7, 8, 10, 13, 16, 17, 19, 21, 23, 29, 30, 31, 32, 35, 41, 47, 48],
 [2, 7, 8, 9, 10, 14, 16],
 [0,
  1,
  3,
  5,
  6,
  10,
  13,
  14,
  15,
  18,
  21,
  24,
  25,
  30,
  33,
  34,
  38,
  42,
  44,
  46,
  47,
  49,
  50,
  52,
  53,
  55,
  57,
  58,
  60,
  61],
 [1, 2, 3, 6, 8, 18, 20, 21],
 [0, 6, 7, 11, 16, 18, 19, 26, 29, 31, 32],
 [3, 4, 5, 7, 8, 11, 14, 21, 22, 23, 25, 26, 30, 31],
 [1, 2, 4, 5, 9, 11, 14, 15],
 [0, 1, 2, 3, 4, 6, 8, 10, 12, 13, 14],
 [2, 3, 4, 5, 6, 10, 11],
 [0, 1, 2, 6, 11],
 [1, 3, 4, 5, 7, 9, 10],
 [0, 6, 9, 10, 11, 14, 16, 18, 19, 20],
 [1, 4, 5, 6, 11, 12, 13, 14, 15],
 [0, 1, 3, 4, 9, 12, 17, 19, 21, 23, 24, 26]]

In [16]:
save_results("bes", bes)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9874869655891554, 'f1': 0.9874918745009784, 'mcc': 0.975056752273994}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.9079754601226994, 'f1': 0.9071438167313856, 'mcc': 0.816963675754572}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7254335260115607, 'f1': 0.7259912194388956, 'mcc': 0.45939192532027373}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 0.9935897435897436, 'f1': 0.99360335962677, 'mcc': 0.9859982319299483}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9574132492113565, 'f1': 0.9573015248670893, 'mcc': 0.9503577605699715}
Processed processed_Hepatitis.csv: {'accuracy': 0.9054054054054054, 'f1': 0.9052476016331439, 'mcc': 0.8083100252766001}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7419354838709677, 'f1': 0.7419354838709677, 'mcc': 0.4700854700854701}
Processed processed_Primary Tumor.csv: {'accuracy': 0.5358490566037736, 'f1': 0.4964202736615894, 'mcc': 0.527007356252485}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9855491329479769, 'f1': 0.9852457792535604, 'mcc': 0.9849790845861702}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9926174496644296, 'f1': 0.9926110339853463, 'mcc': 0.9889447765556918}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.9854771784232366, 'f1': 0.9854818712983384, 'mcc': 0.9711387190156804}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.85, 'f1': 0.849906191369606, 'mcc': 0.7008766440504623}
Processed processed_Credit Approval.csv: {'accuracy': 0.8792270531400966, 'f1': 0.8793118080678329, 'mcc': 0.7582599891020614}
Processed processed_HCV.csv: {'accuracy': 0.995, 'f1': 0.9949976744044804, 'mcc': 0.9937571456842841}
Processed processed_Parkinsons.csv: {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.855072463768116, 'f1': 0.8555443606971155, 'mcc': 0.7823175495403022}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.9802555168408827, 'f1': 0.9802555168408827, 'mcc': 0.9605136783035666}
Processed processed_Lymphography.csv: {'accuracy': 0.9591836734693877, 'f1': 0.9590916563024554, 'mcc': 0.9464761884864643}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9883040935672515, 'f1': 0.9882634226881201, 'mcc': 0.9750124874325203}

In [17]:
STR = """
[ 4 11 17]
[ 0 3 5 6 7 8 9 10 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[ 2 4 5 10 11 15 16 17 18 19 20 21 23 25 28 31 32 33 34 35 36]
[ 1 2 3 4 5 10 15 17 18]
[ 0 1 2 3 6 8 10 11 12 13 15]
[ 1 2 3 12 13 14]
[ 0 1 2 3 4 8 9 11 13 15 17]
[ 1 2 3 4 6 7 8 11 12 14 19 20 22 25 26 27 28 30 33 35 36 41 43 48]
[ 0 2 4 5 6 7 8 9 10 11 13 14 15 16]
[ 0 1 4 5 6 7 8 11 12 14 15 17 19 23 27 28 29 31 32 35 37 38 41 44 46 47 48 49 50 52 53 55 57 58 59]
[ 8 9 10 12 15 16 19 21]
[ 0 4 5 7 12 15 17 19 25 26 27 29 31 32]
[ 0 3 8 11 12 14 16 18 20 23 25 27 29 32]
[ 1 2 3 4 9 10 11 12 13 14 15]
[ 1  2  8 10 13 14]
[ 2  3  5  6  9 10 11]
[ 1  2  3  6  7 11 12]
[ 0  1  3  5  6  7 10]
[ 0  5  7  8 12 13 14 16 18 22 24]
[ 1  2  3  6  7 11 12]
[ 3 5 10 11 12 13 15 17 19 21 22 26 29]
"""

cso = get_features(STR)
cso

[[4, 11, 17],
 [0,
  3,
  5,
  6,
  7,
  8,
  9,
  10,
  12,
  13,
  14,
  15,
  16,
  17,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35],
 [2,
  4,
  5,
  10,
  11,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  23,
  25,
  28,
  31,
  32,
  33,
  34,
  35,
  36],
 [1, 2, 3, 4, 5, 10, 15, 17, 18],
 [0, 1, 2, 3, 6, 8, 10, 11, 12, 13, 15],
 [1, 2, 3, 12, 13, 14],
 [0, 1, 2, 3, 4, 8, 9, 11, 13, 15, 17],
 [1,
  2,
  3,
  4,
  6,
  7,
  8,
  11,
  12,
  14,
  19,
  20,
  22,
  25,
  26,
  27,
  28,
  30,
  33,
  35,
  36,
  41,
  43,
  48],
 [0, 2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16],
 [0,
  1,
  4,
  5,
  6,
  7,
  8,
  11,
  12,
  14,
  15,
  17,
  19,
  23,
  27,
  28,
  29,
  31,
  32,
  35,
  37,
  38,
  41,
  44,
  46,
  47,
  48,
  49,
  50,
  52,
  53,
  55,
  57,
  58,
  59],
 [8, 9, 10, 12, 15, 16, 19, 21],
 [0, 4, 5, 7, 12, 15, 17, 19, 25, 26, 27, 29, 31, 32],
 [0, 3, 8, 11, 12, 14, 16, 18, 20, 23, 25, 27, 29, 32],
 [1, 2, 3, 4, 9, 10, 11, 12, 13, 14, 15],
 [1, 2, 8, 10, 13, 14],
 [2, 3, 5, 6, 9, 10, 11],
 [1, 2, 3, 6, 7, 11, 12],
 [0, 1, 3, 5, 6, 7, 10],
 [0, 5, 7, 8, 12, 13, 14, 16, 18, 22, 24],
 [1, 2, 3, 6, 7, 11, 12],
 [3, 5, 10, 11, 12, 13, 15, 17, 19, 21, 22, 26, 29]]

In [18]:
save_results("cso", cso)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9885297184567258, 'f1': 0.9885276159878897, 'mcc': 0.9770004235206365}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8834355828220859, 'f1': 0.8823821678597551, 'mcc': 0.7664362315701686}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7312138728323699, 'f1': 0.7319412652254422, 'mcc': 0.46435433933133735}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9637223974763407, 'f1': 0.9637575714048641, 'mcc': 0.9576635355350991}
Processed processed_Hepatitis.csv: {'accuracy': 0.8918918918918919, 'f1': 0.8918918918918919, 'mcc': 0.7812269031781227}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7419354838709677, 'f1': 0.743010752688172, 'mcc': 0.5084928361809214}
Processed processed_Primary Tumor.csv: {'accuracy': 0.7867924528301887, 'f1': 0.7821136900453227, 'mcc': 0.7772183375923174}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9884393063583815, 'f1': 0.9882479366419031, 'mcc': 0.9879834773189355}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9939597315436242, 'f1': 0.993961503729744, 'mcc': 0.9909334189377422}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.983402489626556, 'f1': 0.9834084957562403, 'mcc': 0.9670822725555813}
Processed processed_Dermatology.csv: {'accuracy': 0.9851485148514851, 'f1': 0.985102817974105, 'mcc': 0.9823868789088221}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8625, 'f1': 0.8624402952670429, 'mcc': 0.7256301609186202}
Processed processed_Credit Approval.csv: {'accuracy': 0.8792270531400966, 'f1': 0.8792609900412164, 'mcc': 0.757680898976099}
Processed processed_HCV.csv: {'accuracy': 0.99375, 'f1': 0.9937534282166338, 'mcc': 0.9922126374346155}
Processed processed_Parkinsons.csv: {'accuracy': 0.9550561797752809, 'f1': 0.9552160409244542, 'mcc': 0.9134651633484239}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8647342995169082, 'f1': 0.8648821243443717, 'mcc': 0.7968962367539464}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.9825783972125436, 'f1': 0.9825783972125436, 'mcc': 0.9651594453137646}
Processed processed_Lymphography.csv: {'accuracy': 0.9081632653061225, 'f1': 0.9073261957844362, 'mcc': 0.8776219003965039}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9883040935672515, 'f1': 0.9882634226881201, 'mcc': 0.9750124874325203}

In [19]:
STR = """
[17]
[ 0 2 3 5 6 7 8 9 10 12 13 14 15 17 18 19 20 22 24 26 27 29 31 32 34]
[ 0 2 6 10 13 15 16 17 20 21 24 28 29 32 37]
[ 0 2 4 5 7 9 14 16 17]
[ 0 1 2 3 6 8 10 11]
[1 2 3 4 7]
[ 0 3 6 8 12 13 15]
[ 1 3 4 7 11 14 19 21 23 25 38 43 46 48]
[ 0 4 8 10 15 16]
[ 0 1 3 5 6 9 13 14 15 20 22 28 29 31 33 36 37 39 40 47 48 49 50 51 52 53 54 56 58]
[ 2 6 18 19 21]
[ 0 1 3 7 16 18 31]
[ 1 4 5 6 14 15 21 23 24 25 27]
[ 1 2 3 4 9 13 15]
[ 0  1  2  4  8 10 13 14]
[ 0  1  2  3  4  5  6 10 11]
[ 0  1  3  4  5 12]
[ 0  1  2  5  6  9 10]
[ 0  1 10 14 16 18 22 23]
[ 1  2  5  6 13 14 15 17]
[ 3 8 13 19 22 23 24 25 29]
"""

dmoa = get_features(STR)
dmoa

[[17],
 [0,
  2,
  3,
  5,
  6,
  7,
  8,
  9,
  10,
  12,
  13,
  14,
  15,
  17,
  18,
  19,
  20,
  22,
  24,
  26,
  27,
  29,
  31,
  32,
  34],
 [0, 2, 6, 10, 13, 15, 16, 17, 20, 21, 24, 28, 29, 32, 37],
 [0, 2, 4, 5, 7, 9, 14, 16, 17],
 [0, 1, 2, 3, 6, 8, 10, 11],
 [1, 2, 3, 4, 7],
 [0, 3, 6, 8, 12, 13, 15],
 [1, 3, 4, 7, 11, 14, 19, 21, 23, 25, 38, 43, 46, 48],
 [0, 4, 8, 10, 15, 16],
 [0,
  1,
  3,
  5,
  6,
  9,
  13,
  14,
  15,
  20,
  22,
  28,
  29,
  31,
  33,
  36,
  37,
  39,
  40,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  56,
  58],
 [2, 6, 18, 19, 21],
 [0, 1, 3, 7, 16, 18, 31],
 [1, 4, 5, 6, 14, 15, 21, 23, 24, 25, 27],
 [1, 2, 3, 4, 9, 13, 15],
 [0, 1, 2, 4, 8, 10, 13, 14],
 [0, 1, 2, 3, 4, 5, 6, 10, 11],
 [0, 1, 3, 4, 5, 12],
 [0, 1, 2, 5, 6, 9, 10],
 [0, 1, 10, 14, 16, 18, 22, 23],
 [1, 2, 5, 6, 13, 14, 15, 17],
 [3, 8, 13, 19, 22, 23, 24, 25, 29]]

In [20]:
save_results("dmoa", dmoa)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9906152241918665, 'f1': 0.9906135039900916, 'mcc': 0.9811857476734984}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8895705521472392, 'f1': 0.8887192613065612, 'mcc': 0.7783000779444331}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7254335260115607, 'f1': 0.7261223207267775, 'mcc': 0.45049216743197185}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9589905362776026, 'f1': 0.9590144065761447, 'mcc': 0.9521467152437525}
Processed processed_Hepatitis.csv: {'accuracy': 0.8243243243243243, 'f1': 0.8245509190782823, 'mcc': 0.6457817293777938}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7741935483870968, 'f1': 0.7727288578901482, 'mcc': 0.5325124418027843}
Processed processed_Primary Tumor.csv: {'accuracy': 0.4358490566037736, 'f1': 0.3508951741803264, 'mcc': 0.4196462561541112}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9855491329479769, 'f1': 0.9850461193791534, 'mcc': 0.984996028145619}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9939597315436242, 'f1': 0.9939574003303546, 'mcc': 0.9909375008674581}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.983402489626556, 'f1': 0.9834070669084902, 'mcc': 0.966904116896513}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8625, 'f1': 0.8624402952670429, 'mcc': 0.7256301609186202}
Processed processed_Credit Approval.csv: {'accuracy': 0.8840579710144928, 'f1': 0.8839763676720199, 'mcc': 0.7670584794868246}
Processed processed_HCV.csv: {'accuracy': 0.995, 'f1': 0.9949998657001987, 'mcc': 0.9937503666781632}
Processed processed_Parkinsons.csv: {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8743961352657005, 'f1': 0.8742376074175291, 'mcc': 0.8112097365763113}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.9802555168408827, 'f1': 0.9802554635724341, 'mcc': 0.9605215589712964}
Processed processed_Lymphography.csv: {'accuracy': 0.9591836734693877, 'f1': 0.9591182626896914, 'mcc': 0.9460813023604577}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9941520467836257, 'f1': 0.9941421295173417, 'mcc': 0.9874706558674105}

In [21]:
STR = """
[ 1 2 12 17]
[ 2 5 7 9 14 16 17 18 19 20 21 22 23 24 28 31 32]
[ 0 2 6 7 8 10 15 17 20 21 22 23 27 29 34 35 36 37 38]
[ 2 5 6 7 9 10 11 12 14 16 17]
[ 0 1 2 3 4 5 8 9 11 13 14 15]
[ 1 2 3 12]
[ 0 7 8 10 11 13]
[ 1 3 4 5 7 9 10 13 16 17 21 23 25 26 27 30 31 33 37 38 42 43 45 48]
[ 0 2 4 6 7 9 12 14 16]
[ 0 1 3 5 6 10 13 14 18 20 21 22 25 31 32 33 34 35 38 39 41 43 49 55 56 58 59 60 61]
[ 3 4 9 15 19 21]
[ 0 1 4 5 6 9 11 17 18 20 22 24 27 28 31]
[ 3 5 7 11 12 14 19 20 21 25 26 27 30]
[ 1 2 4 6 7 9 11 13 14 15]
[ 2  3  4  8  9 10 12 13 14]
[ 2  3  4  5  6 10 11]
[ 2  3  4  6  9 10 12]
[ 0  1  2  3  5  6  7  8  9 10]
[ 0  3  6 12 14 16 18 19 20 24]
[ 1  2  3 10 12 13 14 15 16]
[ 0 1 4 11 12 15 16 17 24]
"""

eho = get_features(STR)
eho

[[1, 2, 12, 17],
 [2, 5, 7, 9, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 28, 31, 32],
 [0, 2, 6, 7, 8, 10, 15, 17, 20, 21, 22, 23, 27, 29, 34, 35, 36, 37, 38],
 [2, 5, 6, 7, 9, 10, 11, 12, 14, 16, 17],
 [0, 1, 2, 3, 4, 5, 8, 9, 11, 13, 14, 15],
 [1, 2, 3, 12],
 [0, 7, 8, 10, 11, 13],
 [1,
  3,
  4,
  5,
  7,
  9,
  10,
  13,
  16,
  17,
  21,
  23,
  25,
  26,
  27,
  30,
  31,
  33,
  37,
  38,
  42,
  43,
  45,
  48],
 [0, 2, 4, 6, 7, 9, 12, 14, 16],
 [0,
  1,
  3,
  5,
  6,
  10,
  13,
  14,
  18,
  20,
  21,
  22,
  25,
  31,
  32,
  33,
  34,
  35,
  38,
  39,
  41,
  43,
  49,
  55,
  56,
  58,
  59,
  60,
  61],
 [3, 4, 9, 15, 19, 21],
 [0, 1, 4, 5, 6, 9, 11, 17, 18, 20, 22, 24, 27, 28, 31],
 [3, 5, 7, 11, 12, 14, 19, 20, 21, 25, 26, 27, 30],
 [1, 2, 4, 6, 7, 9, 11, 13, 14, 15],
 [2, 3, 4, 8, 9, 10, 12, 13, 14],
 [2, 3, 4, 5, 6, 10, 11],
 [2, 3, 4, 6, 9, 10, 12],
 [0, 1, 2, 3, 5, 6, 7, 8, 9, 10],
 [0, 3, 6, 12, 14, 16, 18, 19, 20, 24],
 [1, 2, 3, 10, 12, 13, 14, 15, 16],
 [0, 1, 4, 11, 12, 15, 16, 17, 24]]

In [22]:
save_results("eho", eho)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9572471324296142, 'f1': 0.9572621356428553, 'mcc': 0.9143995381700953}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8957055214723927, 'f1': 0.8941209312419292, 'mcc': 0.7962941782025197}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7312138728323699, 'f1': 0.7316698346582287, 'mcc': 0.47255926959760486}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9621451104100947, 'f1': 0.9621631041092417, 'mcc': 0.9558372737962619}
Processed processed_Hepatitis.csv: {'accuracy': 0.9054054054054054, 'f1': 0.9052476016331439, 'mcc': 0.8083100252766001}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7903225806451613, 'f1': 0.7914828509498917, 'mcc': 0.5790108009936435}
Processed processed_Primary Tumor.csv: {'accuracy': 0.720754716981132, 'f1': 0.7048918404846944, 'mcc': 0.7087350509431747}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9797687861271677, 'f1': 0.9790622477369119, 'mcc': 0.9790236660553664}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9926174496644296, 'f1': 0.9926173005878246, 'mcc': 0.9889172081477062}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.9854771784232366, 'f1': 0.985478367981959, 'mcc': 0.9709176633330362}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801655841259802, 'mcc': 0.9762846121618856}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8541666666666666, 'f1': 0.8537375285124759, 'mcc': 0.712526820421104}
Processed processed_Credit Approval.csv: {'accuracy': 0.893719806763285, 'f1': 0.8934346452581781, 'mcc': 0.787159190517237}
Processed processed_HCV.csv: {'accuracy': 0.995, 'f1': 0.9949976744044804, 'mcc': 0.9937571456842841}
Processed processed_Parkinsons.csv: {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8671497584541062, 'f1': 0.867519002317774, 'mcc': 0.8004961625108294}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.980836236933798, 'f1': 0.9808362433965075, 'mcc': 0.9616731224890747}
Processed processed_Lymphography.csv: {'accuracy': 0.9795918367346939, 'f1': 0.9795918367346939, 'mcc': 0.9727777777777777}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9941520467836257, 'f1': 0.9941421295173417, 'mcc': 0.9874706558674105}

In [23]:
STR = """
[15 17 18]
[ 0 1 3 5 6 8 9 10 11 13 14 15 16 20 22 24 27 29 32 33 34 35]
[ 2 5 9 10 11 13 14 15 16 17 20 25 26 29 30 31 34 35 36 37 38]
[ 0 1 2 6 8 9 10 11 12 13 14 17 18]
[ 0 1 2 3 6 7 8 9 10 11]
[ 0 1 2 3 7 15]
[ 1 3 4 7 10 11 13 17]
[ 0 8 10 11 15 16 17 20 21 23 25 28 30 33 34 35 41 42 43 48]
[ 0 4 8 10 13 14 16]
[ 0 1 3 5 6 9 13 14 15 18 19 24 30 31 35 36 37 38 39 40 41 42 46 47 48 49 53 54 56 57 58 60]
[ 4 6 9 17 19 21]
[ 0 1 9 11 13 18 19 26 27 28 31 32]
[ 1 3 5 8 9 12 13 14 17 20 22 25 26 29 31]
[ 1 2 3 4 9 10 11 13 15]
[ 2  3  8  9 10 11 13 14]
[ 2  3  5  6 10 11]
[ 2  4  5  6  8  9 12]
[ 0  1  3  5  6  7 10]
[ 0  3  7 11 13 14 15 16 18 20 24]
[ 1  2  3  4  5  6 10 11 12 13 14 15]
[ 1 3 4 5 14 21 22 23 26 29]
"""
ffa = get_features(STR)
ffa

[[15, 17, 18],
 [0,
  1,
  3,
  5,
  6,
  8,
  9,
  10,
  11,
  13,
  14,
  15,
  16,
  20,
  22,
  24,
  27,
  29,
  32,
  33,
  34,
  35],
 [2,
  5,
  9,
  10,
  11,
  13,
  14,
  15,
  16,
  17,
  20,
  25,
  26,
  29,
  30,
  31,
  34,
  35,
  36,
  37,
  38],
 [0, 1, 2, 6, 8, 9, 10, 11, 12, 13, 14, 17, 18],
 [0, 1, 2, 3, 6, 7, 8, 9, 10, 11],
 [0, 1, 2, 3, 7, 15],
 [1, 3, 4, 7, 10, 11, 13, 17],
 [0,
  8,
  10,
  11,
  15,
  16,
  17,
  20,
  21,
  23,
  25,
  28,
  30,
  33,
  34,
  35,
  41,
  42,
  43,
  48],
 [0, 4, 8, 10, 13, 14, 16],
 [0,
  1,
  3,
  5,
  6,
  9,
  13,
  14,
  15,
  18,
  19,
  24,
  30,
  31,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  46,
  47,
  48,
  49,
  53,
  54,
  56,
  57,
  58,
  60],
 [4, 6, 9, 17, 19, 21],
 [0, 1, 9, 11, 13, 18, 19, 26, 27, 28, 31, 32],
 [1, 3, 5, 8, 9, 12, 13, 14, 17, 20, 22, 25, 26, 29, 31],
 [1, 2, 3, 4, 9, 10, 11, 13, 15],
 [2, 3, 8, 9, 10, 11, 13, 14],
 [2, 3, 5, 6, 10, 11],
 [2, 4, 5, 6, 8, 9, 12],
 [0, 1, 3, 5, 6, 7, 10],
 [0, 3, 7, 11, 13, 14, 15, 16, 18, 20, 24],
 [1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15],
 [1, 3, 4, 5, 14, 21, 22, 23, 26, 29]]

In [24]:
save_results("ffa", ffa, datasets=datasets, save_dir="./MCC_F1_results/high_dim")

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9812304483837331, 'f1': 0.9812378117514676, 'mcc': 0.9625152266910424}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.901840490797546, 'f1': 0.9010837878280543, 'mcc': 0.8034962870218796}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7369942196531792, 'f1': 0.7374403758483742, 'mcc': 0.4842066201661168}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9700315457413249, 'f1': 0.9700693658578876, 'mcc': 0.9650165181690924}
Processed processed_Hepatitis.csv: {'accuracy': 0.8918918918918919, 'f1': 0.8918918918918919, 'mcc': 0.7812269031781227}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7580645161290323, 'f1': 0.7596482781339482, 'mcc': 0.5229763603684907}
Processed processed_Primary Tumor.csv: {'accuracy': 0.49433962264150944, 'f1': 0.4309787077846889, 'mcc': 0.47654499319880006}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9884393063583815, 'f1': 0.9879137573243698, 'mcc': 0.988008633455775}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9939597315436242, 'f1': 0.9939589648639414, 'mcc': 0.9909323841816507}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.983402489626556, 'f1': 0.9834084957562403, 'mcc': 0.9670822725555813}
Processed processed_Dermatology.csv: {'accuracy': 0.9851485148514851, 'f1': 0.985102817974105, 'mcc': 0.9823868789088221}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8625, 'f1': 0.8624976128057779, 'mcc': 0.7250251749223126}
Processed processed_Credit Approval.csv: {'accuracy': 0.8792270531400966, 'f1': 0.8792609900412164, 'mcc': 0.757680898976099}
Processed processed_HCV.csv: {'accuracy': 0.9925, 'f1': 0.9925000881988707, 'mcc': 0.9906528907160498}
Processed processed_Parkinsons.csv: {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8647342995169082, 'f1': 0.8648821243443717, 'mcc': 0.7968962367539464}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.9802555168408827, 'f1': 0.9802555168408827, 'mcc': 0.9605109804133168}
Processed processed_Lymphography.csv: {'accuracy': 0.9591836734693877, 'f1': 0.9590916563024554, 'mcc': 0.9464761884864643}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9883040935672515, 'f1': 0.9882634226881201, 'mcc': 0.9750124874325203}

In [25]:
def get_featuresv2(STR):
    return [[int(num) for num in line.strip().split(", ")] for line in STR.strip().replace("[","").replace("]","").replace("[ ","").replace("  "," ").split('\n')]

In [26]:
STR = """
[0, 1, 2, 3, 4, 17]
[0, 1, 2, 4, 5, 7, 9, 10, 13, 14, 15, 18, 20, 24, 25, 26, 28, 29, 30, 31, 32, 34]
[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 19, 24, 26, 30, 31, 32, 33, 35, 38]
[0, 1, 2, 3, 4, 5, 6, 8, 9, 11, 15, 16, 18]
[0, 1, 2, 3, 8, 9, 11, 13, 14, 15]
[0, 1, 2, 3, 7, 9, 12, 14]
[0, 3, 4, 10, 11]
[0, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 16, 18, 20, 22, 25, 26, 27, 30, 32, 36, 37, 43, 46, 47, 48]
[4, 5, 6, 7, 8, 10, 11, 14, 15]
[0, 1, 3, 5, 6, 7, 8, 9, 10, 11, 13, 14, 16, 17, 20, 21, 23, 24, 26, 27, 30, 32, 35, 36, 37, 49, 50, 53, 54, 56, 58, 59]
[2, 6, 12, 13, 17, 19, 21]
[2, 10, 14, 16, 17, 19, 26, 27, 31, 32]
[1, 3, 4, 5, 6, 7, 11, 14, 15, 16, 19, 21, 22, 24, 25, 30, 33]
[1, 4, 6, 8, 10, 11, 12, 14, 15]
[0, 3, 4, 5, 8, 9, 11, 12]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 3, 4, 6, 9, 12]
[0, 1, 3, 5, 6, 7, 8, 9, 10]
[0, 1, 3, 5, 6, 7, 8, 9, 10]
[1, 8, 9, 12, 16]
[0, 1, 2, 12, 14, 15, 21, 22, 23, 24, 26, 29]
"""

ffs = get_featuresv2(STR)
ffs

[[0, 1, 2, 3, 4, 17],
 [0,
  1,
  2,
  4,
  5,
  7,
  9,
  10,
  13,
  14,
  15,
  18,
  20,
  24,
  25,
  26,
  28,
  29,
  30,
  31,
  32,
  34],
 [4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  19,
  24,
  26,
  30,
  31,
  32,
  33,
  35,
  38],
 [0, 1, 2, 3, 4, 5, 6, 8, 9, 11, 15, 16, 18],
 [0, 1, 2, 3, 8, 9, 11, 13, 14, 15],
 [0, 1, 2, 3, 7, 9, 12, 14],
 [0, 3, 4, 10, 11],
 [0,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  11,
  12,
  13,
  14,
  16,
  18,
  20,
  22,
  25,
  26,
  27,
  30,
  32,
  36,
  37,
  43,
  46,
  47,
  48],
 [4, 5, 6, 7, 8, 10, 11, 14, 15],
 [0,
  1,
  3,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  13,
  14,
  16,
  17,
  20,
  21,
  23,
  24,
  26,
  27,
  30,
  32,
  35,
  36,
  37,
  49,
  50,
  53,
  54,
  56,
  58,
  59],
 [2, 6, 12, 13, 17, 19, 21],
 [2, 10, 14, 16, 17, 19, 26, 27, 31, 32],
 [1, 3, 4, 5, 6, 7, 11, 14, 15, 16, 19, 21, 22, 24, 25, 30, 33],
 [1, 4, 6, 8, 10, 11, 12, 14, 15],
 [0, 3, 4, 5, 8, 9, 11, 12],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [1, 3, 4, 6, 9, 12],
 [0, 1, 3, 5, 6, 7, 8, 9, 10],
 [0, 1, 3, 5, 6, 7, 8, 9, 10],
 [1, 8, 9, 12, 16],
 [0, 1, 2, 12, 14, 15, 21, 22, 23, 24, 26, 29]]

In [27]:
save_results("ffs", ffs)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9697601668404588, 'f1': 0.9697772946464399, 'mcc': 0.9397726074826822}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8098159509202454, 'f1': 0.8080972212448637, 'mcc': 0.6148538990169583}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.6820809248554913, 'f1': 0.6820809248554913, 'mcc': 0.379091369701064}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 0.9871794871794872, 'f1': 0.9871794871794872, 'mcc': 0.971677559912854}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9526813880126183, 'f1': 0.9528104824113478, 'mcc': 0.9447621043896481}
Processed processed_Hepatitis.csv: {'accuracy': 0.8513513513513513, 'f1': 0.8511033739949403, 'mcc': 0.6985578383583094}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7580645161290323, 'f1': 0.7586431553410542, 'mcc': 0.5061195626653521}
Processed processed_Primary Tumor.csv: {'accuracy': 0.5075471698113208, 'f1': 0.46728644153002785, 'mcc': 0.49135598326983054}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9710982658959537, 'f1': 0.9708037880383484, 'mcc': 0.9699311827750379}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9932885906040269, 'f1': 0.9932853995632301, 'mcc': 0.9899344311538182}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.979253112033195, 'f1': 0.9792616902968043, 'mcc': 0.9590208178431744}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.7708333333333334, 'f1': 0.770797520445903, 'mcc': 0.5418360168870516}
Processed processed_Credit Approval.csv: {'accuracy': 0.8260869565217391, 'f1': 0.8258090879372343, 'mcc': 0.6504358167736062}
Processed processed_HCV.csv: {'accuracy': 0.99, 'f1': 0.9900293684363827, 'mcc': 0.9875439052687865}
Processed processed_Parkinsons.csv: {'accuracy': 0.898876404494382, 'f1': 0.8991063179362289, 'mcc': 0.8162413858657254}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8526570048309179, 'f1': 0.8527038157229551, 'mcc': 0.7786126399858431}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.835075493612079, 'f1': 0.835028761756668, 'mcc': 0.6705710349949205}
Processed processed_Lymphography.csv: {'accuracy': 0.8877551020408163, 'f1': 0.886829731892757, 'mcc': 0.8506322817655705}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9824561403508771, 'f1': 0.9823623542652152, 'mcc': 0.9626219022237789}

In [28]:
STR = """
[13, 14, 15, 16, 17, 18]
[0, 2, 3, 5, 6, 9, 13, 14, 15, 16, 17, 19, 20, 22, 24, 27, 28, 29, 31, 32, 33, 34]
[1, 2, 4, 6, 7, 9, 10, 11, 16, 18, 19, 20, 23, 26, 27, 28, 30, 32, 33, 34, 35, 38]
[0, 1, 2, 3, 4, 5, 6, 7, 10, 13, 16, 17, 18]
[0, 1, 2, 3, 7, 8, 10, 13, 14, 15]
[1, 2, 3, 5, 7, 9, 10, 11]
[2, 11, 12, 13, 14]
[1, 2, 5, 6, 8, 10, 11, 13, 14, 16, 17, 18, 19, 25, 26, 27, 29, 30, 31, 32, 34, 35, 36, 38, 40, 45, 46, 48]
[1, 4, 7, 8, 9, 10, 12, 13, 14]
[0, 1, 2, 3, 5, 6, 7, 9, 10, 11, 12, 14, 18, 19, 21, 24, 31, 33, 34, 35, 37, 38, 46, 48, 49, 51, 52, 54, 56, 58, 59, 61]
[2, 6, 12, 13, 17, 19, 21]
[0, 1, 2, 3, 10, 19, 24, 30, 31, 32]
[4, 6, 7, 9, 14, 18, 19, 21, 22, 23, 25, 26, 27, 28, 30, 32, 33]
[0, 1, 3, 4, 5, 7, 9, 10, 15]
[3, 4, 7, 8, 10, 11, 13, 14]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 3, 4, 8, 9, 12]
[0, 1, 3, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 5, 6, 7, 8, 9, 10]
[1, 7, 12, 14, 16]
[1, 3, 6, 8, 11, 12, 14, 15, 21, 23, 26, 28]
"""
bfs = get_featuresv2(STR)
bfs

[[13, 14, 15, 16, 17, 18],
 [0,
  2,
  3,
  5,
  6,
  9,
  13,
  14,
  15,
  16,
  17,
  19,
  20,
  22,
  24,
  27,
  28,
  29,
  31,
  32,
  33,
  34],
 [1,
  2,
  4,
  6,
  7,
  9,
  10,
  11,
  16,
  18,
  19,
  20,
  23,
  26,
  27,
  28,
  30,
  32,
  33,
  34,
  35,
  38],
 [0, 1, 2, 3, 4, 5, 6, 7, 10, 13, 16, 17, 18],
 [0, 1, 2, 3, 7, 8, 10, 13, 14, 15],
 [1, 2, 3, 5, 7, 9, 10, 11],
 [2, 11, 12, 13, 14],
 [1,
  2,
  5,
  6,
  8,
  10,
  11,
  13,
  14,
  16,
  17,
  18,
  19,
  25,
  26,
  27,
  29,
  30,
  31,
  32,
  34,
  35,
  36,
  38,
  40,
  45,
  46,
  48],
 [1, 4, 7, 8, 9, 10, 12, 13, 14],
 [0,
  1,
  2,
  3,
  5,
  6,
  7,
  9,
  10,
  11,
  12,
  14,
  18,
  19,
  21,
  24,
  31,
  33,
  34,
  35,
  37,
  38,
  46,
  48,
  49,
  51,
  52,
  54,
  56,
  58,
  59,
  61],
 [2, 6, 12, 13, 17, 19, 21],
 [0, 1, 2, 3, 10, 19, 24, 30, 31, 32],
 [4, 6, 7, 9, 14, 18, 19, 21, 22, 23, 25, 26, 27, 28, 30, 32, 33],
 [0, 1, 3, 4, 5, 7, 9, 10, 15],
 [3, 4, 7, 8, 10, 11, 13, 14],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [1, 3, 4, 8, 9, 12],
 [0, 1, 3, 5, 6, 7, 8, 9, 10],
 [0, 1, 2, 5, 6, 7, 8, 9, 10],
 [1, 7, 12, 14, 16],
 [1, 3, 6, 8, 11, 12, 14, 15, 21, 23, 26, 28]]

In [29]:
save_results("bfs", bfs)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.986444212721585, 'f1': 0.9864477591250231, 'mcc': 0.972874231671622}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8404907975460123, 'f1': 0.8388240992231571, 'mcc': 0.6786264332149439}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.684971098265896, 'f1': 0.6852316332494113, 'mcc': 0.3824719958585721}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 0.9935897435897436, 'f1': 0.99360335962677, 'mcc': 0.9859982319299483}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.943217665615142, 'f1': 0.9436256639448469, 'mcc': 0.9339098552878807}
Processed processed_Hepatitis.csv: {'accuracy': 0.8108108108108109, 'f1': 0.8113652113652113, 'mcc': 0.6252863350010923}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7419354838709677, 'f1': 0.7402615518744551, 'mcc': 0.46540721539674246}
Processed processed_Primary Tumor.csv: {'accuracy': 0.5924528301886792, 'f1': 0.5366331810272208, 'mcc': 0.5777418045604794}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9797687861271677, 'f1': 0.9798881807552329, 'mcc': 0.9789783525582586}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9932885906040269, 'f1': 0.9932853995632301, 'mcc': 0.9899344311538182}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.979253112033195, 'f1': 0.9792606196953005, 'mcc': 0.9587752197269714}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8, 'f1': 0.7999444290080577, 'mcc': 0.6003336113685631}
Processed processed_Credit Approval.csv: {'accuracy': 0.8454106280193237, 'f1': 0.8455407537533142, 'mcc': 0.6908692432298643}
Processed processed_HCV.csv: {'accuracy': 0.99, 'f1': 0.9900293684363827, 'mcc': 0.9875439052687865}
Processed processed_Parkinsons.csv: {'accuracy': 0.9213483146067416, 'f1': 0.9216269037517146, 'mcc': 0.8538913483474397}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8526570048309179, 'f1': 0.8527038157229551, 'mcc': 0.7786126399858431}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.8414634146341463, 'f1': 0.8414632542414431, 'mcc': 0.6829318302471021}
Processed processed_Lymphography.csv: {'accuracy': 0.9081632653061225, 'f1': 0.9069107184608703, 'mcc': 0.8783879813813854}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9824561403508771, 'f1': 0.9824263885520251, 'mcc': 0.9622529912686459}

In [30]:
save_results("qefs", qefs127)

Processed processed_Autism Screening Adult.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Chess (King-Rook vs. King-Pawn).csv: {'accuracy': 0.9343065693430657, 'f1': 0.9343349155596511, 'mcc': 0.8685012126765174}
Processed processed_Cylinder Bands.csv: {'accuracy': 0.8711656441717791, 'f1': 0.8696267269099955, 'mcc': 0.7428885908004075}
Processed processed_Diabetic Retinopathy Debrecen.csv: {'accuracy': 0.7225433526011561, 'f1': 0.7232583513243727, 'mcc': 0.45005475094854713}
Processed processed_Early Stage Diabetes Risk.csv: {'accuracy': 0.9871794871794872, 'f1': 0.9871794871794872, 'mcc': 0.971677559912854}
Processed processed_Estimation of obesity levels based on eating habits and physical condition.csv: {'accuracy': 0.9511041009463722, 'f1': 0.9511096797127353, 'mcc': 0.9429674628687893}
Processed processed_Hepatitis.csv: {'accuracy': 0.8243243243243243, 'f1': 0.8245509190782823, 'mcc': 0.6457817293777938}
Processed processed_Hepatocellular Carcinoma.csv: {'accuracy': 0.7903225806451613, 'f1': 0.7908240679622471, 'mcc': 0.5720426989789064}
Processed processed_Primary Tumor.csv: {'accuracy': 0.6396226415094339, 'f1': 0.6265662199882698, 'mcc': 0.6261461422439982}
Processed processed_Audiology (Standardized).csv: {'accuracy': 0.9479768786127167, 'f1': 0.946565043041358, 'mcc': 0.9459859055756172}
Processed processed_Cardiotocography.csv: {'accuracy': 0.9926174496644296, 'f1': 0.9926166558799094, 'mcc': 0.9889172081477062}
Processed processed_Cervical Cancer.csv: {'accuracy': 0.975103734439834, 'f1': 0.9751127436343605, 'mcc': 0.9504681668983614}
Processed processed_Dermatology.csv: {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}
Processed processed_Thoracic Surgery.csv: {'accuracy': 0.8666666666666667, 'f1': 0.8666296193387052, 'mcc': 0.733741080561577}
Processed processed_Credit Approval.csv: {'accuracy': 0.8695652173913043, 'f1': 0.8696018692445137, 'mcc': 0.7382916115378431}
Processed processed_HCV.csv: {'accuracy': 0.9925, 'f1': 0.9925049547513612, 'mcc': 0.9906201982680665}
Processed processed_Parkinsons.csv: {'accuracy': 0.9325842696629213, 'f1': 0.9328404084559954, 'mcc': 0.8733078876700168}
Processed processed_QSAR Bioconcentration classes.csv: {'accuracy': 0.8599033816425121, 'f1': 0.8600083139405391, 'mcc': 0.7897652958921264}
Processed processed_Thyroid Disease.csv: {'accuracy': 0.980836236933798, 'f1': 0.9808362175456689, 'mcc': 0.9616784148803239}
Processed processed_Lymphography.csv: {'accuracy': 0.9591836734693877, 'f1': 0.9591836734693877, 'mcc': 0.9455555555555556}
Processed processed_Breast Cancer Wisconsin (Diagnostic).csv: {'accuracy': 0.9824561403508771, 'f1': 0.9823623542652152, 'mcc': 0.9626219022237789}

In [34]:
algo_names = ["qefs", "aco", "bes", "cso", "dmoa", "eho", "ffa", "ffs", "bfs"]

table = []
for dataset in datasets:
    row = []
    for algo in algo_names:
        algo_data = json.load(open(f"./MCC_F1_results/high_dim/{algo}.json", "r"))
        print(algo, dataset, algo_data)

        if(dataset in algo_data['bal']):
            # row.append(f"{round(algo_data['bal'][dataset]['accuracy'], 3)},{round(algo_data['bal'][dataset]['mcc'], 3)},{round(algo_data['bal'][dataset]['f1'], 3)}")
            row.append(f"{round(algo_data['bal'][dataset]['mcc'], 3)},{round(algo_data['bal'][dataset]['f1'], 3)}")
        
        elif(dataset in algo_data['imbal']):
            #row.append(f"{round(algo_data['imbal'][dataset]['accuracy'], 3)},{round(algo_data['imbal'][dataset]['mcc'], 3)},{round(algo_data['imbal'][dataset]['f1'], 3)}")
            row.append(f"{round(algo_data['imbal'][dataset]['mcc'], 3)},{round(algo_data['imbal'][dataset]['f1'], 3)}")

    table.append(row)

df = pd.DataFrame(table)
df.columns = ['QEFS', 'ACO', 'BES', 'CSO', 'DMOA', 'EHO', 'FFA', 'FFS', 'BFS']
df.index = datasets

qefs processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9343065693430657, 'f1': 0.9343349155596511, 'mcc': 0.8685012126765174}, 'processed_Cylinder Bands.csv': {'accuracy': 0.8711656441717791, 'f1': 0.8696267269099955, 'mcc': 0.7428885908004075}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7225433526011561, 'f1': 0.7232583513243727, 'mcc': 0.45005475094854713}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 0.9871794871794872, 'f1': 0.9871794871794872, 'mcc': 0.971677559912854}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9511041009463722, 'f1': 0.9511096797127353, 'mcc': 0.9429674628687893}, 'processed_Credit Approval.csv': {'accuracy': 0.8695652173913043, 'f1': 0.8696018692445137, 'mcc': 0.7382916115378431}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9824561403508771, 'f1': 0.9823623542652152, 'mcc': 0.9626219022237789}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.8243243243243243, 'f1': 0.8245509190782823, 'mcc': 0.6457817293777938}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7903225806451613, 'f1': 0.7908240679622471, 'mcc': 0.5720426989789064}, 'processed_Primary Tumor.csv': {'accuracy': 0.6396226415094339, 'f1': 0.6265662199882698, 'mcc': 0.6261461422439982}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9479768786127167, 'f1': 0.946565043041358, 'mcc': 0.9459859055756172}, 'processed_Cardiotocography.csv': {'accuracy': 0.9926174496644296, 'f1': 0.9926166558799094, 'mcc': 0.9889172081477062}, 'processed_Cervical Cancer.csv': {'accuracy': 0.975103734439834, 'f1': 0.9751127436343605, 'mcc': 0.9504681668983614}, 'processed_Dermatology.csv': {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.8666666666666667, 'f1': 0.8666296193387052, 'mcc': 0.733741080561577}, 'processed_HCV.csv': {'accuracy': 0.9925, 'f1': 0.9925049547513612, 'mcc': 0.9906201982680665}, 'processed_Parkinsons.csv': {'accuracy': 0.9325842696629213, 'f1': 0.9328404084559954, 'mcc': 0.8733078876700168}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.8599033816425121, 'f1': 0.8600083139405391, 'mcc': 0.7897652958921264}, 'processed_Thyroid Disease.csv': {'accuracy': 0.980836236933798, 'f1': 0.9808362175456689, 'mcc': 0.9616784148803239}, 'processed_Lymphography.csv': {'accuracy': 0.9591836734693877, 'f1': 0.9591836734693877, 'mcc': 0.9455555555555556}}}
aco processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9739311783107404, 'f1': 0.973948550239587, 'mcc': 0.9484027528886612}, 'processed_Cylinder Bands.csv': {'accuracy': 0.8895705521472392, 'f1': 0.8884166840775705, 'mcc': 0.7799696385415915}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7283236994219653, 'f1': 0.7284795191625127, 'mcc': 0.45139879222918877}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9558359621451105, 'f1': 0.9558556193495463, 'mcc': 0.9485202943821591}, 'processed_Credit Approval.csv': {'accuracy': 0.8985507246376812, 'f1': 0.8984363968087564, 'mcc': 0.7962635300467855}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9941520467836257, 'f1': 0.9941421295173417, 'mcc': 0.9874706558674105}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.8378378378378378, 'f1': 0.837234555984556, 'mcc': 0.670904674744761}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7096774193548387, 'f1': 0.7114976236222066, 'mcc': 0.4304142310105583}, 'processed_Primary Tumor.csv': {'accuracy': 0.21320754716981133, 'f1': 0.11596990981559248, 'mcc': 0.20250199333368402}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9826589595375722, 'f1': 0.9825356235456633, 'mcc': 0.9819329736319492}, 'processed_Cardiotocography.csv': {'accuracy': 0.9946308724832215, 'f1': 0.994630645309478, 'mcc': 0.9919418759074042}, 'processed_Cervical Cancer.csv': {'accuracy': 0.9813278008298755, 'f1': 0.9813338345264351, 'mcc': 0.9628310223209914}, 'processed_Dermatology.csv': {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.8583333333333333, 'f1': 0.858323494687131, 'mcc': 0.7167662244453878}, 'processed_HCV.csv': {'accuracy': 0.99375, 'f1': 0.993723558580647, 'mcc': 0.9922134858216433}, 'processed_Parkinsons.csv': {'accuracy': 0.9550561797752809, 'f1': 0.9552160409244542, 'mcc': 0.9134651633484239}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.8671497584541062, 'f1': 0.8675780939883346, 'mcc': 0.8005014477871684}, 'processed_Thyroid Disease.csv': {'accuracy': 0.9819976771196284, 'f1': 0.9819976589065375, 'mcc': 0.9640013030856008}, 'processed_Lymphography.csv': {'accuracy': 0.9693877551020408, 'f1': 0.9693755053041626, 'mcc': 0.9592999120193504}}}
bes processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9874869655891554, 'f1': 0.9874918745009784, 'mcc': 0.975056752273994}, 'processed_Cylinder Bands.csv': {'accuracy': 0.9079754601226994, 'f1': 0.9071438167313856, 'mcc': 0.816963675754572}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7254335260115607, 'f1': 0.7259912194388956, 'mcc': 0.45939192532027373}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 0.9935897435897436, 'f1': 0.99360335962677, 'mcc': 0.9859982319299483}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9574132492113565, 'f1': 0.9573015248670893, 'mcc': 0.9503577605699715}, 'processed_Credit Approval.csv': {'accuracy': 0.8792270531400966, 'f1': 0.8793118080678329, 'mcc': 0.7582599891020614}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9883040935672515, 'f1': 0.9882634226881201, 'mcc': 0.9750124874325203}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.9054054054054054, 'f1': 0.9052476016331439, 'mcc': 0.8083100252766001}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7419354838709677, 'f1': 0.7419354838709677, 'mcc': 0.4700854700854701}, 'processed_Primary Tumor.csv': {'accuracy': 0.5358490566037736, 'f1': 0.4964202736615894, 'mcc': 0.527007356252485}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9855491329479769, 'f1': 0.9852457792535604, 'mcc': 0.9849790845861702}, 'processed_Cardiotocography.csv': {'accuracy': 0.9926174496644296, 'f1': 0.9926110339853463, 'mcc': 0.9889447765556918}, 'processed_Cervical Cancer.csv': {'accuracy': 0.9854771784232366, 'f1': 0.9854818712983384, 'mcc': 0.9711387190156804}, 'processed_Dermatology.csv': {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.85, 'f1': 0.849906191369606, 'mcc': 0.7008766440504623}, 'processed_HCV.csv': {'accuracy': 0.995, 'f1': 0.9949976744044804, 'mcc': 0.9937571456842841}, 'processed_Parkinsons.csv': {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.855072463768116, 'f1': 0.8555443606971155, 'mcc': 0.7823175495403022}, 'processed_Thyroid Disease.csv': {'accuracy': 0.9802555168408827, 'f1': 0.9802555168408827, 'mcc': 0.9605136783035666}, 'processed_Lymphography.csv': {'accuracy': 0.9591836734693877, 'f1': 0.9590916563024554, 'mcc': 0.9464761884864643}}}
cso processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9885297184567258, 'f1': 0.9885276159878897, 'mcc': 0.9770004235206365}, 'processed_Cylinder Bands.csv': {'accuracy': 0.8834355828220859, 'f1': 0.8823821678597551, 'mcc': 0.7664362315701686}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7312138728323699, 'f1': 0.7319412652254422, 'mcc': 0.46435433933133735}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9637223974763407, 'f1': 0.9637575714048641, 'mcc': 0.9576635355350991}, 'processed_Credit Approval.csv': {'accuracy': 0.8792270531400966, 'f1': 0.8792609900412164, 'mcc': 0.757680898976099}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9883040935672515, 'f1': 0.9882634226881201, 'mcc': 0.9750124874325203}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.8918918918918919, 'f1': 0.8918918918918919, 'mcc': 0.7812269031781227}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7419354838709677, 'f1': 0.743010752688172, 'mcc': 0.5084928361809214}, 'processed_Primary Tumor.csv': {'accuracy': 0.7867924528301887, 'f1': 0.7821136900453227, 'mcc': 0.7772183375923174}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9884393063583815, 'f1': 0.9882479366419031, 'mcc': 0.9879834773189355}, 'processed_Cardiotocography.csv': {'accuracy': 0.9939597315436242, 'f1': 0.993961503729744, 'mcc': 0.9909334189377422}, 'processed_Cervical Cancer.csv': {'accuracy': 0.983402489626556, 'f1': 0.9834084957562403, 'mcc': 0.9670822725555813}, 'processed_Dermatology.csv': {'accuracy': 0.9851485148514851, 'f1': 0.985102817974105, 'mcc': 0.9823868789088221}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.8625, 'f1': 0.8624402952670429, 'mcc': 0.7256301609186202}, 'processed_HCV.csv': {'accuracy': 0.99375, 'f1': 0.9937534282166338, 'mcc': 0.9922126374346155}, 'processed_Parkinsons.csv': {'accuracy': 0.9550561797752809, 'f1': 0.9552160409244542, 'mcc': 0.9134651633484239}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.8647342995169082, 'f1': 0.8648821243443717, 'mcc': 0.7968962367539464}, 'processed_Thyroid Disease.csv': {'accuracy': 0.9825783972125436, 'f1': 0.9825783972125436, 'mcc': 0.9651594453137646}, 'processed_Lymphography.csv': {'accuracy': 0.9081632653061225, 'f1': 0.9073261957844362, 'mcc': 0.8776219003965039}}}
dmoa processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9906152241918665, 'f1': 0.9906135039900916, 'mcc': 0.9811857476734984}, 'processed_Cylinder Bands.csv': {'accuracy': 0.8895705521472392, 'f1': 0.8887192613065612, 'mcc': 0.7783000779444331}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7254335260115607, 'f1': 0.7261223207267775, 'mcc': 0.45049216743197185}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9589905362776026, 'f1': 0.9590144065761447, 'mcc': 0.9521467152437525}, 'processed_Credit Approval.csv': {'accuracy': 0.8840579710144928, 'f1': 0.8839763676720199, 'mcc': 0.7670584794868246}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9941520467836257, 'f1': 0.9941421295173417, 'mcc': 0.9874706558674105}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.8243243243243243, 'f1': 0.8245509190782823, 'mcc': 0.6457817293777938}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7741935483870968, 'f1': 0.7727288578901482, 'mcc': 0.5325124418027843}, 'processed_Primary Tumor.csv': {'accuracy': 0.4358490566037736, 'f1': 0.3508951741803264, 'mcc': 0.4196462561541112}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9855491329479769, 'f1': 0.9850461193791534, 'mcc': 0.984996028145619}, 'processed_Cardiotocography.csv': {'accuracy': 0.9939597315436242, 'f1': 0.9939574003303546, 'mcc': 0.9909375008674581}, 'processed_Cervical Cancer.csv': {'accuracy': 0.983402489626556, 'f1': 0.9834070669084902, 'mcc': 0.966904116896513}, 'processed_Dermatology.csv': {'accuracy': 0.9801980198019802, 'f1': 0.9801980198019802, 'mcc': 0.9761722205838985}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.8625, 'f1': 0.8624402952670429, 'mcc': 0.7256301609186202}, 'processed_HCV.csv': {'accuracy': 0.995, 'f1': 0.9949998657001987, 'mcc': 0.9937503666781632}, 'processed_Parkinsons.csv': {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.8743961352657005, 'f1': 0.8742376074175291, 'mcc': 0.8112097365763113}, 'processed_Thyroid Disease.csv': {'accuracy': 0.9802555168408827, 'f1': 0.9802554635724341, 'mcc': 0.9605215589712964}, 'processed_Lymphography.csv': {'accuracy': 0.9591836734693877, 'f1': 0.9591182626896914, 'mcc': 0.9460813023604577}}}
eho processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9572471324296142, 'f1': 0.9572621356428553, 'mcc': 0.9143995381700953}, 'processed_Cylinder Bands.csv': {'accuracy': 0.8957055214723927, 'f1': 0.8941209312419292, 'mcc': 0.7962941782025197}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7312138728323699, 'f1': 0.7316698346582287, 'mcc': 0.47255926959760486}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9621451104100947, 'f1': 0.9621631041092417, 'mcc': 0.9558372737962619}, 'processed_Credit Approval.csv': {'accuracy': 0.893719806763285, 'f1': 0.8934346452581781, 'mcc': 0.787159190517237}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9941520467836257, 'f1': 0.9941421295173417, 'mcc': 0.9874706558674105}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.9054054054054054, 'f1': 0.9052476016331439, 'mcc': 0.8083100252766001}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7903225806451613, 'f1': 0.7914828509498917, 'mcc': 0.5790108009936435}, 'processed_Primary Tumor.csv': {'accuracy': 0.720754716981132, 'f1': 0.7048918404846944, 'mcc': 0.7087350509431747}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9797687861271677, 'f1': 0.9790622477369119, 'mcc': 0.9790236660553664}, 'processed_Cardiotocography.csv': {'accuracy': 0.9926174496644296, 'f1': 0.9926173005878246, 'mcc': 0.9889172081477062}, 'processed_Cervical Cancer.csv': {'accuracy': 0.9854771784232366, 'f1': 0.985478367981959, 'mcc': 0.9709176633330362}, 'processed_Dermatology.csv': {'accuracy': 0.9801980198019802, 'f1': 0.9801655841259802, 'mcc': 0.9762846121618856}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.8541666666666666, 'f1': 0.8537375285124759, 'mcc': 0.712526820421104}, 'processed_HCV.csv': {'accuracy': 0.995, 'f1': 0.9949976744044804, 'mcc': 0.9937571456842841}, 'processed_Parkinsons.csv': {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.8671497584541062, 'f1': 0.867519002317774, 'mcc': 0.8004961625108294}, 'processed_Thyroid Disease.csv': {'accuracy': 0.980836236933798, 'f1': 0.9808362433965075, 'mcc': 0.9616731224890747}, 'processed_Lymphography.csv': {'accuracy': 0.9795918367346939, 'f1': 0.9795918367346939, 'mcc': 0.9727777777777777}}}
ffa processed_Autism Screening Adult.csv {'bal': {'processed_Chess (King-Rook vs. King-Pawn).csv': {'accuracy': 0.9812304483837331, 'f1': 0.9812378117514676, 'mcc': 0.9625152266910424}, 'processed_Cylinder Bands.csv': {'accuracy': 0.901840490797546, 'f1': 0.9010837878280543, 'mcc': 0.8034962870218796}, 'processed_Diabetic Retinopathy Debrecen.csv': {'accuracy': 0.7369942196531792, 'f1': 0.7374403758483742, 'mcc': 0.4842066201661168}, 'processed_Early Stage Diabetes Risk.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Estimation of obesity levels based on eating habits and physical condition.csv': {'accuracy': 0.9700315457413249, 'f1': 0.9700693658578876, 'mcc': 0.9650165181690924}, 'processed_Credit Approval.csv': {'accuracy': 0.8792270531400966, 'f1': 0.8792609900412164, 'mcc': 0.757680898976099}, 'processed_Breast Cancer Wisconsin (Diagnostic).csv': {'accuracy': 0.9883040935672515, 'f1': 0.9882634226881201, 'mcc': 0.9750124874325203}}, 'imbal': {'processed_Autism Screening Adult.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_Hepatitis.csv': {'accuracy': 0.8918918918918919, 'f1': 0.8918918918918919, 'mcc': 0.7812269031781227}, 'processed_Hepatocellular Carcinoma.csv': {'accuracy': 0.7580645161290323, 'f1': 0.7596482781339482, 'mcc': 0.5229763603684907}, 'processed_Primary Tumor.csv': {'accuracy': 0.49433962264150944, 'f1': 0.4309787077846889, 'mcc': 0.47654499319880006}, 'processed_Audiology (Standardized).csv': {'accuracy': 0.9884393063583815, 'f1': 0.9879137573243698, 'mcc': 0.988008633455775}, 'processed_Cardiotocography.csv': {'accuracy': 0.9939597315436242, 'f1': 0.9939589648639414, 'mcc': 0.9909323841816507}, 'processed_Cervical Cancer.csv': {'accuracy': 0.983402489626556, 'f1': 0.9834084957562403, 'mcc': 0.9670822725555813}, 'processed_Dermatology.csv': {'accuracy': 0.9851485148514851, 'f1': 0.985102817974105, 'mcc': 0.9823868789088221}, 'processed_Thoracic Surgery.csv': {'accuracy': 0.8625, 'f1': 0.8624976128057779, 'mcc': 0.7250251749223126}, 'processed_HCV.csv': {'accuracy': 0.9925, 'f1': 0.9925000881988707, 'mcc': 0.9906528907160498}, 'processed_Parkinsons.csv': {'accuracy': 0.9438202247191011, 'f1': 0.9440339714861812, 'mcc': 0.8931557942079718}, 'processed_QSAR Bioconcentration classes.csv': {'accuracy': 0.8647342995169082, 'f1': 0.8648821243443717, 'mcc': 0.7968962367539464}, 'processed_Thyroid Disease.csv': {'accuracy': 0.9802555168408827, 'f1': 0.9802555168408827, 'mcc': 0.9605109804133168}, 'processed_Lymphography.csv': {'accuracy': 0.9591836734693877, 'f1': 0.9590916563024554, 'mcc': 0.9464761884864643}}}

In [35]:
df.index = [name.replace("processed_","").replace(".csv","") for name in df.index]

In [36]:
df

,QEFS,ACO,BES,CSO,DMOA,EHO,FFA,FFS,BFS
Autism Screening Adult,"1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0"
Chess (King-Rook vs. King-Pawn),"0.869,0.934","0.948,0.974","0.975,0.987","0.977,0.989","0.981,0.991","0.914,0.957","0.963,0.981","0.94,0.97","0.973,0.986"
Cylinder Bands,"0.743,0.87","0.78,0.888","0.817,0.907","0.766,0.882","0.778,0.889","0.796,0.894","0.803,0.901","0.615,0.808","0.679,0.839"
Diabetic Retinopathy Debrecen,"0.45,0.723","0.451,0.728","0.459,0.726","0.464,0.732","0.45,0.726","0.473,0.732","0.484,0.737","0.379,0.682","0.382,0.685"
Early Stage Diabetes Risk,"0.972,0.987","1.0,1.0","0.986,0.994","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","0.972,0.987","0.986,0.994"
Estimation of obesity levels based on eating habits and physical condition,"0.943,0.951","0.949,0.956","0.95,0.957","0.958,0.964","0.952,0.959","0.956,0.962","0.965,0.97","0.945,0.953","0.934,0.944"
Hepatitis,"0.646,0.825","0.671,0.837","0.808,0.905","0.781,0.892","0.646,0.825","0.808,0.905","0.781,0.892","0.699,0.851","0.625,0.811"
Hepatocellular Carcinoma,"0.572,0.791","0.43,0.711","0.47,0.742","0.508,0.743","0.533,0.773","0.579,0.791","0.523,0.76","0.506,0.759","0.465,0.74"
Primary Tumor,"0.626,0.627","0.203,0.116","0.527,0.496","0.777,0.782","0.42,0.351","0.709,0.705","0.477,0.431","0.491,0.467","0.578,0.537"
Audiology (Standardized),"0.946,0.947","0.982,0.983","0.985,0.985","0.988,0.988","0.985,0.985","0.979,0.979","0.988,0.988","0.97,0.971","0.979,0.98"
Cardiotocography,"0.989,0.993","0.992,0.995","0.989,0.993","0.991,0.994","0.991,0.994","0.989,0.993","0.991,0.994","0.99,0.993","0.99,0.993"
Cervical Cancer,"0.95,0.975","0.963,0.981","0.971,0.985","0.967,0.983","0.967,0.983","0.971,0.985","0.967,0.983","0.959,0.979","0.959,0.979"
Dermatology,"0.976,0.98","0.976,0.98","0.976,0.98","0.982,0.985","0.976,0.98","0.976,0.98","0.982,0.985","0.976,0.98","0.976,0.98"
Thoracic Surgery,"0.734,0.867","0.717,0.858","0.701,0.85","0.726,0.862","0.726,0.862","0.713,0.854","0.725,0.862","0.542,0.771","0.6,0.8"
Credit Approval,"0.738,0.87","0.796,0.898","0.758,0.879","0.758,0.879","0.767,0.884","0.787,0.893","0.758,0.879","0.65,0.826","0.691,0.846"
HCV,"0.991,0.993","0.992,0.994","0.994,0.995","0.992,0.994","0.994,0.995","0.994,0.995","0.991,0.993","0.988,0.99","0.988,0.99"
Parkinsons,"0.873,0.933","0.913,0.955","0.893,0.944","0.913,0.955","0.893,0.944","0.893,0.944","0.893,0.944","0.816,0.899","0.854,0.922"
QSAR Bioconcentration classes,"0.79,0.86","0.801,0.868","0.782,0.856","0.797,0.865","0.811,0.874","0.8,0.868","0.797,0.865","0.779,0.853","0.779,0.853"
Thyroid Disease,"0.962,0.981","0.964,0.982","0.961,0.98","0.965,0.983","0.961,0.98","0.962,0.981","0.961,0.98","0.671,0.835","0.683,0.841"
Lymphography,"0.946,0.959","0.959,0.969","0.946,0.959","0.878,0.907","0.946,0.959","0.973,0.98","0.946,0.959","0.851,0.887","0.878,0.907"
Breast Cancer Wisconsin (Diagnostic),"0.963,0.982","0.987,0.994","0.975,0.988","0.975,0.988","0.987,0.994","0.987,0.994","0.975,0.988","0.963,0.982","0.962,0.982"

In [194]:
df.to_csv(f"{save_dir}/high_dim.tsv", sep="\t")

#<15 Dimensional Datasets

In [37]:
"""
processed_Dishonest Internet users.csv
processed_Hayes Roth.csv
processed_ILPD (Indian Liver Patient Dataset).csv
processed_Liver Disorders.csv
processed_Abalone.csv
processed_Blood Transfusion Service.csv
processed_Breast Cancer.csv
processed_Climate Model Simulation Crashes.csv
processed_Fertility.csv
processed_Heart Disease.csv
""".split("\n")

['',
 'processed_Dishonest Internet users.csv',
 'processed_Hayes Roth.csv',
 'processed_ILPD (Indian Liver Patient Dataset).csv',
 'processed_Liver Disorders.csv',
 'processed_Abalone.csv',
 'processed_Blood Transfusion Service.csv',
 'processed_Breast Cancer.csv',
 'processed_Climate Model Simulation Crashes.csv',
 'processed_Fertility.csv',
 'processed_Heart Disease.csv',
 '']

In [38]:
l_datasets = [
 'processed_Dishonest Internet users.csv',
 'processed_Hayes Roth.csv',
 'processed_ILPD (Indian Liver Patient Dataset).csv',
 'processed_Liver Disorders.csv',
 'processed_Abalone.csv',
 'processed_Blood Transfusion Service.csv',
 'processed_Breast Cancer.csv',
 'processed_Climate Model Simulation Crashes.csv',
 'processed_Fertility.csv',
 'processed_Heart Disease.csv',
 ]

l_datasets

['processed_Dishonest Internet users.csv',
 'processed_Hayes Roth.csv',
 'processed_ILPD (Indian Liver Patient Dataset).csv',
 'processed_Liver Disorders.csv',
 'processed_Abalone.csv',
 'processed_Blood Transfusion Service.csv',
 'processed_Breast Cancer.csv',
 'processed_Climate Model Simulation Crashes.csv',
 'processed_Fertility.csv',
 'processed_Heart Disease.csv']

In [39]:
STR = """
[0, 2, 3]
[1, 2, 3]
[0, 1, 4, 5, 7, 8, 9]
[0, 1, 2, 3, 5]
[0, 1, 4, 5, 6]
[0, 2, 3]
[0, 3, 4, 5, 6, 7, 8]
[0]
[0, 1, 2, 3, 6, 8]
[2, 4, 5, 7, 8, 9, 11]
"""
qefs = get_featuresv2(STR)
qefs

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 4, 5, 7, 8, 9],
 [0, 1, 2, 3, 5],
 [0, 1, 4, 5, 6],
 [0, 2, 3],
 [0, 3, 4, 5, 6, 7, 8],
 [0],
 [0, 1, 2, 3, 6, 8],
 [2, 4, 5, 7, 8, 9, 11]]

In [40]:
save_results("qefs", qefs, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.752, 'f1': 0.7524458140729328, 'mcc': 0.5039878398218515}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8899447131997236, 'f1': 0.8842746940486665, 'mcc': 0.885945305749831}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9622641509433962, 'f1': 0.9622641509433962, 'mcc': 0.9242857142857143}
Processed processed_Heart Disease.csv: {'accuracy': 0.8536585365853658, 'f1': 0.8511709519524742, 'mcc': 0.818818516310859}

In [41]:
STR = """
[0 2 3]
[1 2 3]
[0 1 2 4 6 8 9]
[0 1 2 3 5]
[1 2 3 4 6 7]
[0 1 3]
[0 3 4 5 6 7 8]
[0]
[3 5 6]
[ 0 1 2 4 6 7 8 9 10 11 12]
"""
aco = get_features(STR)
aco

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 2, 4, 6, 8, 9],
 [0, 1, 2, 3, 5],
 [1, 2, 3, 4, 6, 7],
 [0, 1, 3],
 [0, 3, 4, 5, 6, 7, 8],
 [0],
 [3, 5, 6],
 [0, 1, 2, 4, 6, 7, 8, 9, 10, 11, 12]]

In [42]:
save_results("aco", aco, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}
Processed processed_Heart Disease.csv: {'accuracy': 0.8739837398373984, 'f1': 0.8706278281609625, 'mcc': 0.8439830803852418}

In [43]:
STR = """
[0 2 3]
[1 2 3]
[0 1 2 4 6 8 9]
[0 1 2 3 5]
[1 2 3 4 6 7]
[0 1 3]
[0 3 4 5 6 7 8]
[0]
[2 3 5 6 8]
[ 2 3 4 7 9 10 11 12]
"""
bes = get_features(STR)
bes

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 2, 4, 6, 8, 9],
 [0, 1, 2, 3, 5],
 [1, 2, 3, 4, 6, 7],
 [0, 1, 3],
 [0, 3, 4, 5, 6, 7, 8],
 [0],
 [2, 3, 5, 6, 8],
 [2, 3, 4, 7, 9, 10, 11, 12]]

In [44]:
save_results("bes", bes, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}
Processed processed_Heart Disease.csv: {'accuracy': 0.8536585365853658, 'f1': 0.8508405126848408, 'mcc': 0.8183984352384491}

In [45]:
STR = """
[0 2 3]
[1 2 3]
[0 1 2 4 6 8 9]
[0 1 2 3 5]
[1 2 3 4 6 7]
[0 2 3]
[0 1 2 3 4 5 6 7 8]
[0]
[1 6]
[ 1 2 3 4 5 6 7 8 9 10 11 12]
"""

cso = get_features(STR)
cso

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 2, 4, 6, 8, 9],
 [0, 1, 2, 3, 5],
 [1, 2, 3, 4, 6, 7],
 [0, 2, 3],
 [0, 1, 2, 3, 4, 5, 6, 7, 8],
 [0],
 [1, 6],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]

In [46]:
save_results("cso", cso, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8091603053435115, 'f1': 0.8094050144000157, 'mcc': 0.6297273879845682}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}
Processed processed_Heart Disease.csv: {'accuracy': 0.8821138211382114, 'f1': 0.8811707387005593, 'mcc': 0.8525889296035951}

In [47]:
STR = """
[0 2 3]
[1 2 3]
[0 1 2 4 5 6 8]
[0 1 2 3 5]
[0 2 3 5 6 7]
[0 2 3]
[0 3 4 5 6 7 8]
[0]
[1 6]
[ 2 4 5 6 7 9 10 11 12]
"""
dmoa = get_features(STR)
dmoa

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 2, 4, 5, 6, 8],
 [0, 1, 2, 3, 5],
 [0, 2, 3, 5, 6, 7],
 [0, 2, 3],
 [0, 3, 4, 5, 6, 7, 8],
 [0],
 [1, 6],
 [2, 4, 5, 6, 7, 9, 10, 11, 12]]

In [48]:
save_results("dmoa", dmoa, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.792, 'f1': 0.7916501035196688, 'mcc': 0.5798634957496238}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8934001382170007, 'f1': 0.8886069819023932, 'mcc': 0.88955795099214}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}
Processed processed_Heart Disease.csv: {'accuracy': 0.8739837398373984, 'f1': 0.8733815277869149, 'mcc': 0.8421881367752774}

In [49]:
STR = """
[0 2 3]
[1 2 3]
[1 2 4 6]
[0 1 2 3 5]
[1 2 3 4 6 7]
[0 1 3]
[3 4 5 6 7]
[0]
[1 2 3 5 6 8]
[ 2 4 5 6 7 9 10 11 12]
"""
eho = get_features(STR)
eho

[[0, 2, 3],
 [1, 2, 3],
 [1, 2, 4, 6],
 [0, 1, 2, 3, 5],
 [1, 2, 3, 4, 6, 7],
 [0, 1, 3],
 [3, 4, 5, 6, 7],
 [0],
 [1, 2, 3, 5, 6, 8],
 [2, 4, 5, 6, 7, 9, 10, 11, 12]]

In [50]:
save_results("eho", eho, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.776, 'f1': 0.7763454790823212, 'mcc': 0.5510571514368227}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8015267175572519, 'f1': 0.8020138539447341, 'mcc': 0.6053013035543401}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}
Processed processed_Heart Disease.csv: {'accuracy': 0.8739837398373984, 'f1': 0.8733815277869149, 'mcc': 0.8421881367752774}

In [51]:
STR = """
[0 2 3]
[1 2 3]
[0 1 2 4 6 8 9]
[0 1 2 3 5]
[1 2 3 4 6 7]
[0 2 3]
[0 3 4 5 6 7 8]
[0]
[1 6]
[ 1 2 3 4 5 6 7 8 9 10 11 12]
"""
ffa = get_features(STR)
ffa

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 2, 4, 6, 8, 9],
 [0, 1, 2, 3, 5],
 [1, 2, 3, 4, 6, 7],
 [0, 2, 3],
 [0, 3, 4, 5, 6, 7, 8],
 [0],
 [1, 6],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]

In [52]:
save_results("ffa", ffa, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}
Processed processed_Abalone.csv: {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}
Processed processed_Breast Cancer.csv: {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}
Processed processed_Heart Disease.csv: {'accuracy': 0.8821138211382114, 'f1': 0.8811707387005593, 'mcc': 0.8525889296035951}

In [53]:
STR = """
[0, 1, 3]
[1, 2, 3]
[0, 1, 2, 3, 5, 8, 9]
[1, 2, 3, 4, 5]
[1, 3, 4, 5, 7]
[0, 1, 2]
[1, 2, 3, 4, 6, 7, 8]
[0]
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 7, 8, 9, 11]
"""
ffs = get_featuresv2(STR)
ffs

[[0, 1, 3],
 [1, 2, 3],
 [0, 1, 2, 3, 5, 8, 9],
 [1, 2, 3, 4, 5],
 [1, 3, 4, 5, 7],
 [0, 1, 2],
 [1, 2, 3, 4, 6, 7, 8],
 [0],
 [1, 2, 3, 4, 5, 6],
 [2, 3, 4, 7, 8, 9, 11]]

In [54]:
save_results("ffs", ffs, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.768, 'f1': 0.768268656716418, 'mcc': 0.5339782668149995}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7211538461538461, 'f1': 0.7167896747949241, 'mcc': 0.4206026886299481}
Processed processed_Abalone.csv: {'accuracy': 0.8885625431928127, 'f1': 0.8829682747377574, 'mcc': 0.8845402745717725}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.7573099415204678, 'f1': 0.7553146039478149, 'mcc': 0.5119389531742756}
Processed processed_Breast Cancer.csv: {'accuracy': 0.816793893129771, 'f1': 0.8172215451065922, 'mcc': 0.6391822756498375}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9622641509433962, 'f1': 0.9622641509433962, 'mcc': 0.9242857142857143}
Processed processed_Heart Disease.csv: {'accuracy': 0.8373983739837398, 'f1': 0.8355267883247774, 'mcc': 0.7969630454938417}

In [55]:
STR = """
[0, 2, 3]
[1, 2, 3]
[0, 1, 2, 5, 6, 8, 9]
[1, 2, 3, 4, 5]
[1, 3, 4, 5, 7]
[0, 1, 2]
[1, 2, 3, 4, 6, 7, 8]
[0]
[0, 1, 2, 3, 5, 6]
[1, 2, 3, 4, 7, 10, 11]
"""
bfs = get_featuresv2(STR)
bfs

[[0, 2, 3],
 [1, 2, 3],
 [0, 1, 2, 5, 6, 8, 9],
 [1, 2, 3, 4, 5],
 [1, 3, 4, 5, 7],
 [0, 1, 2],
 [1, 2, 3, 4, 6, 7, 8],
 [0],
 [0, 1, 2, 3, 5, 6],
 [1, 2, 3, 4, 7, 10, 11]]

In [56]:
save_results("bfs", bfs, datasets=l_datasets, save_dir="./MCC_F1_results/low_dim")

Processed processed_Dishonest Internet users.csv: {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}
Processed processed_Hayes Roth.csv: {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}
Processed processed_ILPD (Indian Liver Patient Dataset).csv: {'accuracy': 0.776, 'f1': 0.7762593926917138, 'mcc': 0.5500658260706937}
Processed processed_Liver Disorders.csv: {'accuracy': 0.7211538461538461, 'f1': 0.7167896747949241, 'mcc': 0.4206026886299481}
Processed processed_Abalone.csv: {'accuracy': 0.8885625431928127, 'f1': 0.8829682747377574, 'mcc': 0.8845402745717725}
Processed processed_Blood Transfusion Service.csv: {'accuracy': 0.7573099415204678, 'f1': 0.7553146039478149, 'mcc': 0.5119389531742756}
Processed processed_Breast Cancer.csv: {'accuracy': 0.816793893129771, 'f1': 0.8172215451065922, 'mcc': 0.6391822756498375}
Processed processed_Climate Model Simulation Crashes.csv: {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}
Processed processed_Fertility.csv: {'accuracy': 0.9433962264150944, 'f1': 0.9434365856119463, 'mcc': 0.8873047544726261}
Processed processed_Heart Disease.csv: {'accuracy': 0.8048780487804879, 'f1': 0.8049811326669036, 'mcc': 0.7566191115654614}

In [61]:
algo_names = ["qefs", "aco", "bes", "cso", "dmoa", "eho", "ffa", "ffs", "bfs"]

table = []
for dataset in l_datasets:
    row = []
    for algo in algo_names:
        algo_data = json.load(open(f"./MCC_F1_results/low_dim/{algo}.json", "r"))
        print(algo, dataset, algo_data)

        if(dataset in algo_data['bal']):
            # row.append(f"{round(algo_data['bal'][dataset]['accuracy'], 3)},{round(algo_data['bal'][dataset]['mcc'], 3)},{round(algo_data['bal'][dataset]['f1'], 3)}")
            row.append(f"{round(algo_data['bal'][dataset]['mcc'], 3)},{round(algo_data['bal'][dataset]['f1'], 3)}")
        elif(dataset in algo_data['imbal']):
            row.append(f"{round(algo_data['imbal'][dataset]['mcc'], 3)},{round(algo_data['imbal'][dataset]['f1'], 3)}")

    table.append(row)

df = pd.DataFrame(table)
df.columns = ['QEFS', 'ACO', 'BES', 'CSO', 'DMOA', 'EHO', 'FFA', 'FFS', 'BFS']
df.index = l_datasets

qefs processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.752, 'f1': 0.7524458140729328, 'mcc': 0.5039878398218515}, 'processed_Abalone.csv': {'accuracy': 0.8899447131997236, 'f1': 0.8842746940486665, 'mcc': 0.885945305749831}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9622641509433962, 'f1': 0.9622641509433962, 'mcc': 0.9242857142857143}, 'processed_Heart Disease.csv': {'accuracy': 0.8536585365853658, 'f1': 0.8511709519524742, 'mcc': 0.818818516310859}}}
aco processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}, 'processed_Heart Disease.csv': {'accuracy': 0.8739837398373984, 'f1': 0.8706278281609625, 'mcc': 0.8439830803852418}}}
bes processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}, 'processed_Heart Disease.csv': {'accuracy': 0.8536585365853658, 'f1': 0.8508405126848408, 'mcc': 0.8183984352384491}}}
cso processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8091603053435115, 'f1': 0.8094050144000157, 'mcc': 0.6297273879845682}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}, 'processed_Heart Disease.csv': {'accuracy': 0.8821138211382114, 'f1': 0.8811707387005593, 'mcc': 0.8525889296035951}}}
dmoa processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7916501035196688, 'mcc': 0.5798634957496238}, 'processed_Abalone.csv': {'accuracy': 0.8934001382170007, 'f1': 0.8886069819023932, 'mcc': 0.88955795099214}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}, 'processed_Heart Disease.csv': {'accuracy': 0.8739837398373984, 'f1': 0.8733815277869149, 'mcc': 0.8421881367752774}}}
eho processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.776, 'f1': 0.7763454790823212, 'mcc': 0.5510571514368227}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8015267175572519, 'f1': 0.8020138539447341, 'mcc': 0.6053013035543401}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}, 'processed_Heart Disease.csv': {'accuracy': 0.8739837398373984, 'f1': 0.8733815277869149, 'mcc': 0.8421881367752774}}}
ffa processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}, 'processed_Heart Disease.csv': {'accuracy': 0.8821138211382114, 'f1': 0.8811707387005593, 'mcc': 0.8525889296035951}}}
ffs processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7211538461538461, 'f1': 0.7167896747949241, 'mcc': 0.4206026886299481}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.768, 'f1': 0.768268656716418, 'mcc': 0.5339782668149995}, 'processed_Abalone.csv': {'accuracy': 0.8885625431928127, 'f1': 0.8829682747377574, 'mcc': 0.8845402745717725}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.7573099415204678, 'f1': 0.7553146039478149, 'mcc': 0.5119389531742756}, 'processed_Breast Cancer.csv': {'accuracy': 0.816793893129771, 'f1': 0.8172215451065922, 'mcc': 0.6391822756498375}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9622641509433962, 'f1': 0.9622641509433962, 'mcc': 0.9242857142857143}, 'processed_Heart Disease.csv': {'accuracy': 0.8373983739837398, 'f1': 0.8355267883247774, 'mcc': 0.7969630454938417}}}
bfs processed_Dishonest Internet users.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7211538461538461, 'f1': 0.7167896747949241, 'mcc': 0.4206026886299481}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.776, 'f1': 0.7762593926917138, 'mcc': 0.5500658260706937}, 'processed_Abalone.csv': {'accuracy': 0.8885625431928127, 'f1': 0.8829682747377574, 'mcc': 0.8845402745717725}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.7573099415204678, 'f1': 0.7553146039478149, 'mcc': 0.5119389531742756}, 'processed_Breast Cancer.csv': {'accuracy': 0.816793893129771, 'f1': 0.8172215451065922, 'mcc': 0.6391822756498375}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9433962264150944, 'f1': 0.9434365856119463, 'mcc': 0.8873047544726261}, 'processed_Heart Disease.csv': {'accuracy': 0.8048780487804879, 'f1': 0.8049811326669036, 'mcc': 0.7566191115654614}}}
qefs processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.752, 'f1': 0.7524458140729328, 'mcc': 0.5039878398218515}, 'processed_Abalone.csv': {'accuracy': 0.8899447131997236, 'f1': 0.8842746940486665, 'mcc': 0.885945305749831}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9622641509433962, 'f1': 0.9622641509433962, 'mcc': 0.9242857142857143}, 'processed_Heart Disease.csv': {'accuracy': 0.8536585365853658, 'f1': 0.8511709519524742, 'mcc': 0.818818516310859}}}
aco processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}, 'processed_Heart Disease.csv': {'accuracy': 0.8739837398373984, 'f1': 0.8706278281609625, 'mcc': 0.8439830803852418}}}
bes processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}, 'processed_Heart Disease.csv': {'accuracy': 0.8536585365853658, 'f1': 0.8508405126848408, 'mcc': 0.8183984352384491}}}
cso processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8091603053435115, 'f1': 0.8094050144000157, 'mcc': 0.6297273879845682}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}, 'processed_Heart Disease.csv': {'accuracy': 0.8821138211382114, 'f1': 0.8811707387005593, 'mcc': 0.8525889296035951}}}
dmoa processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7916501035196688, 'mcc': 0.5798634957496238}, 'processed_Abalone.csv': {'accuracy': 0.8934001382170007, 'f1': 0.8886069819023932, 'mcc': 0.88955795099214}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}, 'processed_Heart Disease.csv': {'accuracy': 0.8739837398373984, 'f1': 0.8733815277869149, 'mcc': 0.8421881367752774}}}
eho processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.776, 'f1': 0.7763454790823212, 'mcc': 0.5510571514368227}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8015267175572519, 'f1': 0.8020138539447341, 'mcc': 0.6053013035543401}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.98110505373947, 'mcc': 0.9627546685029047}, 'processed_Heart Disease.csv': {'accuracy': 0.8739837398373984, 'f1': 0.8733815277869149, 'mcc': 0.8421881367752774}}}
ffa processed_Hayes Roth.csv {'bal': {'processed_Hayes Roth.csv': {'accuracy': 0.8, 'f1': 0.8019047619047619, 'mcc': 0.7505101443270885}, 'processed_Liver Disorders.csv': {'accuracy': 0.7596153846153846, 'f1': 0.7583048228672333, 'mcc': 0.503954958614422}}, 'imbal': {'processed_Dishonest Internet users.csv': {'accuracy': 1.0, 'f1': 1.0, 'mcc': 1.0}, 'processed_ILPD (Indian Liver Patient Dataset).csv': {'accuracy': 0.792, 'f1': 0.7923208020050126, 'mcc': 0.5832075103304529}, 'processed_Abalone.csv': {'accuracy': 0.8935729094678645, 'f1': 0.8876708773857811, 'mcc': 0.8897618736046862}, 'processed_Blood Transfusion Service.csv': {'accuracy': 0.783625730994152, 'f1': 0.783625730994152, 'mcc': 0.56510980513455}, 'processed_Breast Cancer.csv': {'accuracy': 0.8244274809160306, 'f1': 0.8247362069914375, 'mcc': 0.6476699723145376}, 'processed_Climate Model Simulation Crashes.csv': {'accuracy': 0.8417508417508418, 'f1': 0.8364764309167387, 'mcc': 0.716486141929616}, 'processed_Fertility.csv': {'accuracy': 0.9811320754716981, 'f1': 0.9811455285373154, 'mcc': 0.962911108149554}, 'processed_Heart Disease.csv': {'accuracy': 0.8821138211382114, 'f1': 0.8811707387005593, 'mcc': 0.8525889296035951}}}

In [62]:
df.index = [name.replace("processed_","").replace(".csv","") for name in df.index]

In [63]:
df

,QEFS,ACO,BES,CSO,DMOA,EHO,FFA,FFS,BFS
Dishonest Internet users,"1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0","1.0,1.0"
Hayes Roth,"0.751,0.802","0.751,0.802","0.751,0.802","0.751,0.802","0.751,0.802","0.751,0.802","0.751,0.802","0.751,0.802","0.751,0.802"
ILPD (Indian Liver Patient Dataset),"0.504,0.752","0.583,0.792","0.583,0.792","0.583,0.792","0.58,0.792","0.551,0.776","0.583,0.792","0.534,0.768","0.55,0.776"
Liver Disorders,"0.504,0.758","0.504,0.758","0.504,0.758","0.504,0.758","0.504,0.758","0.504,0.758","0.504,0.758","0.421,0.717","0.421,0.717"
Abalone,"0.886,0.884","0.89,0.888","0.89,0.888","0.89,0.888","0.89,0.889","0.89,0.888","0.89,0.888","0.885,0.883","0.885,0.883"
Blood Transfusion Service,"0.565,0.784","0.565,0.784","0.565,0.784","0.565,0.784","0.565,0.784","0.565,0.784","0.565,0.784","0.512,0.755","0.512,0.755"
Breast Cancer,"0.648,0.825","0.648,0.825","0.648,0.825","0.63,0.809","0.648,0.825","0.605,0.802","0.648,0.825","0.639,0.817","0.639,0.817"
Climate Model Simulation Crashes,"0.716,0.836","0.716,0.836","0.716,0.836","0.716,0.836","0.716,0.836","0.716,0.836","0.716,0.836","0.716,0.836","0.716,0.836"
Fertility,"0.924,0.962","0.963,0.981","0.963,0.981","0.963,0.981","0.963,0.981","0.963,0.981","0.963,0.981","0.924,0.962","0.887,0.943"
Heart Disease,"0.819,0.851","0.844,0.871","0.818,0.851","0.853,0.881","0.842,0.873","0.842,0.873","0.853,0.881","0.797,0.836","0.757,0.805"

In [64]:
df.to_csv(f"./MCC_F1_results/low_dim/low_dim.tsv", sep="\t")